
ForeverProbeM89DB = {
["sessions"] = {
{
["probe_version"] = "m8-9-probe-0.1",
["baseline"] = {
[1013] = {
["title"] = "The Book of Ur",
["ready"] = false,
["complete"] = false,
["log_index"] = 7,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "item",
["have"] = 0,
["text_info"] = "present",
["text"] = "0/1 The Book of Ur",
["need"] = 1,
["finished"] = false,
},
},
},
[92421] = {
["title"] = "Light's Justice",
["ready"] = true,
["complete"] = true,
["log_index"] = 2,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "item",
["have"] = 25,
["text_info"] = "present",
["text"] = "25/25 Intact Limbs",
["need"] = 25,
["finished"] = true,
},
},
},
[92422] = {
["title"] = "The Wrath of Rath'mael",
["ready"] = true,
["complete"] = true,
["log_index"] = 3,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "monster",
["have"] = 1,
["text_info"] = "present",
["text"] = "1/1 Rath'mael slain",
["need"] = 1,
["finished"] = true,
},
},
},
[93739] = {
["title"] = "Exploring the Horde",
["ready"] = true,
["complete"] = true,
["log_index"] = 5,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "monster",
["have"] = 1,
["text_info"] = "present",
["text"] = "1/1 Obtain Instructions from Nazgrel",
["need"] = 1,
["finished"] = true,
},
{
["type"] = "monster",
["have"] = 1,
["text_info"] = "present",
["text"] = "1/1 Speak with Vol'jin",
["need"] = 1,
["finished"] = true,
},
{
["type"] = "monster",
["have"] = 1,
["text_info"] = "present",
["text"] = "1/1 Speak with Cairne Bloodhoof",
["need"] = 1,
["finished"] = true,
},
{
["type"] = "monster",
["have"] = 1,
["text_info"] = "present",
["text"] = "1/1 Speak with Lady Sylvanas Windrunner",
["need"] = 1,
["finished"] = true,
},
},
},
[92401] = {
["title"] = "A Frightened Request",
["ready"] = true,
["complete"] = true,
["log_index"] = 11,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "event",
["have"] = 1,
["text_info"] = "present",
["text"] = "Investigate the disappearance of Edward Heartweaver in the Ruins of Lordaeron.",
["need"] = 1,
["finished"] = true,
},
},
},
[98024] = {
["title"] = "Journey to the Crossroads",
["ready"] = true,
["complete"] = true,
["log_index"] = 9,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
},
},
},
["build_date"] = "Sep 29 2026",
["toc_version"] = 16001,
["final_t"] = 1169953.197,
["registration"] = {
["UI_INFO_MESSAGE"] = "registered",
["QUEST_REMOVED"] = "registered",
["UNIT_QUEST_LOG_CHANGED"] = "registered",
["QUEST_ACCEPTED"] = "registered",
["QUEST_TURNED_IN"] = "registered",
["QUEST_WATCH_UPDATE"] = "registered",
["QUEST_LOG_UPDATE"] = "registered",
},
["final_snapshot"] = {
[1013] = {
["title"] = "The Book of Ur",
["ready"] = false,
["complete"] = false,
["log_index"] = 4,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "item",
["have"] = 0,
["text_info"] = "present",
["text"] = "0/1 The Book of Ur",
["need"] = 1,
["finished"] = false,
},
},
},
[93739] = {
["title"] = "Exploring the Horde",
["ready"] = true,
["complete"] = true,
["log_index"] = 2,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "monster",
["have"] = 1,
["text_info"] = "present",
["text"] = "1/1 Obtain Instructions from Nazgrel",
["need"] = 1,
["finished"] = true,
},
{
["type"] = "monster",
["have"] = 1,
["text_info"] = "present",
["text"] = "1/1 Speak with Vol'jin",
["need"] = 1,
["finished"] = true,
},
{
["type"] = "monster",
["have"] = 1,
["text_info"] = "present",
["text"] = "1/1 Speak with Cairne Bloodhoof",
["need"] = 1,
["finished"] = true,
},
{
["type"] = "monster",
["have"] = 1,
["text_info"] = "present",
["text"] = "1/1 Speak with Lady Sylvanas Windrunner",
["need"] = 1,
["finished"] = true,
},
},
},
[98024] = {
["title"] = "Journey to the Crossroads",
["ready"] = true,
["complete"] = true,
["log_index"] = 6,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
},
},
[92401] = {
["title"] = "A Frightened Request",
["ready"] = true,
["complete"] = true,
["log_index"] = 8,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "event",
["have"] = 1,
["text_info"] = "present",
["text"] = "Investigate the disappearance of Edward Heartweaver in the Ruins of Lordaeron.",
["need"] = 1,
["finished"] = true,
},
},
},
},
["onupdate_install"] = "installed",
["records"] = {
{
["immediate_change_count"] = 0,
["seq"] = 1,
["args"] = {
["n"] = 0,
},
["t"] = 1169583.074,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
["pre_baseline"] = true,
},
{
["t"] = 1169654.232,
["changes"] = {
{
["quest_id"] = 92421,
["kind"] = "quest_removed",
["title"] = "Light's Justice",
},
},
["quest_snapshots"] = {
},
["meaningful"] = 0,
["seconds_after_trigger"] = 0,
["seq"] = 2,
["kind"] = "change",
["detected_by"] = "event",
["trigger_event"] = "UNIT_QUEST_LOG_CHANGED",
},
{
["args"] = {
{
["value"] = "player",
["type"] = "string",
},
["n"] = 1,
},
["immediate_change_count"] = 1,
["seq"] = 3,
["kind"] = "event",
["event"] = "UNIT_QUEST_LOG_CHANGED",
["t"] = 1169654.232,
},
{
["args"] = {
["n"] = 0,
},
["immediate_change_count"] = 0,
["seq"] = 4,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
["t"] = 1169654.232,
},
{
["args"] = {
{
["value"] = 92421,
["type"] = "number",
},
{
["value"] = false,
["type"] = "boolean",
},
["n"] = 2,
},
["kind"] = "context",
["t"] = 1169654.232,
["seq"] = 5,
["event"] = "QUEST_REMOVED",
},
{
["args"] = {
{
["value"] = 92421,
["type"] = "number",
},
{
["value"] = 7050,
["type"] = "number",
},
{
["value"] = 4500,
["type"] = "number",
},
["n"] = 3,
},
["kind"] = "context",
["t"] = 1169654.336,
["seq"] = 6,
["event"] = "QUEST_TURNED_IN",
},
{
["args"] = {
["n"] = 0,
},
["immediate_change_count"] = 0,
["seq"] = 7,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
["t"] = 1169654.336,
},
{
["args"] = {
["n"] = 0,
},
["immediate_change_count"] = 0,
["seq"] = 8,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
["t"] = 1169684.616,
},
{
["args"] = {
["n"] = 0,
},
["immediate_change_count"] = 0,
["seq"] = 9,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
["t"] = 1169691.691,
},
{
["args"] = {
["n"] = 0,
},
["immediate_change_count"] = 0,
["seq"] = 10,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
["t"] = 1169712.848,
},
{
["args"] = {
["n"] = 0,
},
["immediate_change_count"] = 0,
["seq"] = 11,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
["t"] = 1169727.851,
},
{
["kind"] = "manual_snapshot",
["snapshot"] = {
[98024] = {
["title"] = "Journey to the Crossroads",
["ready"] = true,
["complete"] = true,
["log_index"] = 8,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
},
},
[92422] = {
["title"] = "The Wrath of Rath'mael",
["ready"] = true,
["complete"] = true,
["log_index"] = 4,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "monster",
["have"] = 1,
["text_info"] = "present",
["text"] = "1/1 Rath'mael slain",
["need"] = 1,
["finished"] = true,
},
},
},
[93739] = {
["title"] = "Exploring the Horde",
["ready"] = true,
["complete"] = true,
["log_index"] = 2,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "monster",
["have"] = 1,
["text_info"] = "present",
["text"] = "1/1 Obtain Instructions from Nazgrel",
["need"] = 1,
["finished"] = true,
},
{
["type"] = "monster",
["have"] = 1,
["text_info"] = "present",
["text"] = "1/1 Speak with Vol'jin",
["need"] = 1,
["finished"] = true,
},
{
["type"] = "monster",
["have"] = 1,
["text_info"] = "present",
["text"] = "1/1 Speak with Cairne Bloodhoof",
["need"] = 1,
["finished"] = true,
},
{
["type"] = "monster",
["have"] = 1,
["text_info"] = "present",
["text"] = "1/1 Speak with Lady Sylvanas Windrunner",
["need"] = 1,
["finished"] = true,
},
},
},
[92401] = {
["title"] = "A Frightened Request",
["ready"] = true,
["complete"] = true,
["log_index"] = 10,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "event",
["have"] = 1,
["text_info"] = "present",
["text"] = "Investigate the disappearance of Edward Heartweaver in the Ruins of Lordaeron.",
["need"] = 1,
["finished"] = true,
},
},
},
[1013] = {
["title"] = "The Book of Ur",
["ready"] = false,
["complete"] = false,
["log_index"] = 6,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "item",
["have"] = 0,
["text_info"] = "present",
["text"] = "0/1 The Book of Ur",
["need"] = 1,
["finished"] = false,
},
},
},
},
["seq"] = 12,
["t"] = 1169810.036,
},
{
["t"] = 1169900.164,
["changes"] = {
{
["quest_id"] = 92422,
["title"] = "The Wrath of Rath'mael",
["from"] = true,
["kind"] = "complete_changed",
["to"] = false,
},
{
["quest_id"] = 92422,
["title"] = "The Wrath of Rath'mael",
["from"] = true,
["kind"] = "ready_changed",
["to"] = false,
},
{
["quest_id"] = 92422,
["title"] = "The Wrath of Rath'mael",
["from"] = {
["finished"] = true,
["text"] = "1/1 Rath'mael slain",
["need"] = 1,
["have"] = 1,
},
["kind"] = "objective_changed",
["to"] = {
["finished"] = false,
["text"] = "0/1 Rath'mael slain",
["need"] = 1,
["have"] = 0,
},
["index"] = 1,
},
},
["quest_snapshots"] = {
[92422] = {
["title"] = "The Wrath of Rath'mael",
["ready"] = false,
["complete"] = false,
["log_index"] = 4,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "monster",
["have"] = 0,
["text_info"] = "present",
["text"] = "0/1 Rath'mael slain",
["need"] = 1,
["finished"] = false,
},
},
},
},
["meaningful"] = 3,
["seconds_after_trigger"] = 0,
["seq"] = 13,
["kind"] = "change",
["detected_by"] = "event",
["trigger_event"] = "UNIT_QUEST_LOG_CHANGED",
},
{
["args"] = {
{
["value"] = "player",
["type"] = "string",
},
["n"] = 1,
},
["immediate_change_count"] = 3,
["seq"] = 14,
["kind"] = "event",
["event"] = "UNIT_QUEST_LOG_CHANGED",
["t"] = 1169900.164,
},
{
["args"] = {
["n"] = 0,
},
["immediate_change_count"] = 0,
["seq"] = 15,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
["t"] = 1169900.164,
},
{
["args"] = {
{
["value"] = 92422,
["type"] = "number",
},
{
["value"] = false,
["type"] = "boolean",
},
["n"] = 2,
},
["kind"] = "context",
["t"] = 1169900.164,
["seq"] = 16,
["event"] = "QUEST_REMOVED",
},
{
["args"] = {
{
["value"] = 92422,
["type"] = "number",
},
{
["value"] = 0,
["type"] = "number",
},
{
["value"] = 0,
["type"] = "number",
},
["n"] = 3,
},
["kind"] = "context",
["t"] = 1169900.213,
["seq"] = 17,
["event"] = "QUEST_TURNED_IN",
},
{
["t"] = 1169900.213,
["changes"] = {
{
["quest_id"] = 92422,
["kind"] = "quest_removed",
["title"] = "The Wrath of Rath'mael",
},
},
["quest_snapshots"] = {
},
["meaningful"] = 0,
["seconds_after_trigger"] = 0,
["seq"] = 18,
["kind"] = "change",
["detected_by"] = "event",
["trigger_event"] = "QUEST_LOG_UPDATE",
},
{
["args"] = {
["n"] = 0,
},
["immediate_change_count"] = 1,
["seq"] = 19,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
["t"] = 1169900.213,
},
{
["args"] = {
["n"] = 0,
},
["immediate_change_count"] = 0,
["seq"] = 20,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
["t"] = 1169919.796,
},
{
["kind"] = "manual_snapshot",
["snapshot"] = {
[1013] = {
["title"] = "The Book of Ur",
["ready"] = false,
["complete"] = false,
["log_index"] = 4,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "item",
["have"] = 0,
["text_info"] = "present",
["text"] = "0/1 The Book of Ur",
["need"] = 1,
["finished"] = false,
},
},
},
[93739] = {
["title"] = "Exploring the Horde",
["ready"] = true,
["complete"] = true,
["log_index"] = 2,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "monster",
["have"] = 1,
["text_info"] = "present",
["text"] = "1/1 Obtain Instructions from Nazgrel",
["need"] = 1,
["finished"] = true,
},
{
["type"] = "monster",
["have"] = 1,
["text_info"] = "present",
["text"] = "1/1 Speak with Vol'jin",
["need"] = 1,
["finished"] = true,
},
{
["type"] = "monster",
["have"] = 1,
["text_info"] = "present",
["text"] = "1/1 Speak with Cairne Bloodhoof",
["need"] = 1,
["finished"] = true,
},
{
["type"] = "monster",
["have"] = 1,
["text_info"] = "present",
["text"] = "1/1 Speak with Lady Sylvanas Windrunner",
["need"] = 1,
["finished"] = true,
},
},
},
[98024] = {
["title"] = "Journey to the Crossroads",
["ready"] = true,
["complete"] = true,
["log_index"] = 6,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
},
},
[92401] = {
["title"] = "A Frightened Request",
["ready"] = true,
["complete"] = true,
["log_index"] = 8,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "event",
["have"] = 1,
["text_info"] = "present",
["text"] = "Investigate the disappearance of Edward Heartweaver in the Ruins of Lordaeron.",
["need"] = 1,
["finished"] = true,
},
},
},
},
["seq"] = 21,
["t"] = 1169943.53,
},
},
["onupdate_ticks"] = 45134,
["started_t"] = 1169582.08,
["game_version"] = "1.60.1",
["baseline_t"] = 1169585.082,
["apis"] = {
["C_QuestLog.ReadyForTurnIn"] = "function",
["C_QuestLog.IsComplete"] = "function",
["C_Timer.After"] = "function (not used)",
["C_QuestLog.GetInfo"] = "function",
["C_QuestLog.GetTitleForQuestID"] = "function",
["GetQuestLogLeaderBoard"] = "function",
["C_QuestLog.GetQuestObjectives"] = "function",
["GetNumQuestLeaderBoards"] = "function",
["GetNumQuestLogEntries"] = "absent",
["C_QuestLog.GetNumQuestLogEntries"] = "function",
["GetQuestLogTitle"] = "absent",
},
["counts"] = {
["objective_change:event"] = 1,
["QUEST_REMOVED"] = 2,
["complete_changed:event"] = 1,
["UNIT_QUEST_LOG_CHANGED"] = 2,
["quest_removed"] = 2,
["QUEST_TURNED_IN"] = 2,
["ready_changed:event"] = 1,
["QUEST_LOG_UPDATE"] = 10,
},
["build"] = "70124",
},
{
["probe_version"] = "m8-9-probe-0.1",
["baseline"] = {
[1013] = {
["title"] = "The Book of Ur",
["objectives"] = {
{
["type"] = "item",
["have"] = 0,
["text_info"] = "present",
["text"] = "0/1 The Book of Ur",
["need"] = 1,
["finished"] = false,
},
},
["source"] = "C_QuestLog.GetQuestObjectives",
["log_index"] = 4,
["complete"] = false,
["ready"] = false,
},
[93739] = {
["title"] = "Exploring the Horde",
["objectives"] = {
{
["type"] = "monster",
["have"] = 1,
["text_info"] = "present",
["text"] = "1/1 Obtain Instructions from Nazgrel",
["need"] = 1,
["finished"] = true,
},
{
["type"] = "monster",
["have"] = 1,
["text_info"] = "present",
["text"] = "1/1 Speak with Vol'jin",
["need"] = 1,
["finished"] = true,
},
{
["type"] = "monster",
["have"] = 1,
["text_info"] = "present",
["text"] = "1/1 Speak with Cairne Bloodhoof",
["need"] = 1,
["finished"] = true,
},
{
["type"] = "monster",
["have"] = 1,
["text_info"] = "present",
["text"] = "1/1 Speak with Lady Sylvanas Windrunner",
["need"] = 1,
["finished"] = true,
},
},
["source"] = "C_QuestLog.GetQuestObjectives",
["log_index"] = 2,
["complete"] = true,
["ready"] = true,
},
[98024] = {
["title"] = "Journey to the Crossroads",
["objectives"] = {
},
["source"] = "C_QuestLog.GetQuestObjectives",
["log_index"] = 6,
["complete"] = true,
["ready"] = true,
},
[92401] = {
["title"] = "A Frightened Request",
["objectives"] = {
{
["type"] = "event",
["have"] = 1,
["text_info"] = "present",
["text"] = "Investigate the disappearance of Edward Heartweaver in the Ruins of Lordaeron.",
["need"] = 1,
["finished"] = true,
},
},
["source"] = "C_QuestLog.GetQuestObjectives",
["log_index"] = 8,
["complete"] = true,
["ready"] = true,
},
},
["toc_version"] = 16001,
["build_date"] = "Sep 29 2026",
["records"] = {
{
["args"] = {
["n"] = 0,
},
["event"] = "QUEST_LOG_UPDATE",
["immediate_change_count"] = 0,
["kind"] = "event",
["t"] = 1169957.216,
["seq"] = 1,
["pre_baseline"] = true,
},
},
["registration"] = {
["UI_INFO_MESSAGE"] = "registered",
["QUEST_REMOVED"] = "registered",
["UNIT_QUEST_LOG_CHANGED"] = "registered",
["QUEST_ACCEPTED"] = "registered",
["QUEST_TURNED_IN"] = "registered",
["QUEST_WATCH_UPDATE"] = "registered",
["QUEST_LOG_UPDATE"] = "registered",
},
["apis"] = {
["C_QuestLog.ReadyForTurnIn"] = "function",
["C_QuestLog.IsComplete"] = "function",
["C_Timer.After"] = "function (not used)",
["C_QuestLog.GetInfo"] = "function",
["C_QuestLog.GetTitleForQuestID"] = "function",
["GetQuestLogLeaderBoard"] = "function",
["C_QuestLog.GetQuestObjectives"] = "function",
["GetQuestLogTitle"] = "absent",
["GetNumQuestLogEntries"] = "absent",
["C_QuestLog.GetNumQuestLogEntries"] = "function",
["GetNumQuestLeaderBoards"] = "function",
},
["onupdate_install"] = "installed",
["final_t"] = 1169997.999,
["onupdate_ticks"] = 5387,
["game_version"] = "1.60.1",
["started_t"] = 1169956.277,
["baseline_t"] = 1169959.279,
["final_snapshot"] = {
[1013] = {
["title"] = "The Book of Ur",
["objectives"] = {
{
["type"] = "item",
["have"] = 0,
["text_info"] = "present",
["text"] = "0/1 The Book of Ur",
["need"] = 1,
["finished"] = false,
},
},
["source"] = "C_QuestLog.GetQuestObjectives",
["log_index"] = 4,
["complete"] = false,
["ready"] = false,
},
[93739] = {
["title"] = "Exploring the Horde",
["objectives"] = {
{
["type"] = "monster",
["have"] = 1,
["text_info"] = "present",
["text"] = "1/1 Obtain Instructions from Nazgrel",
["need"] = 1,
["finished"] = true,
},
{
["type"] = "monster",
["have"] = 1,
["text_info"] = "present",
["text"] = "1/1 Speak with Vol'jin",
["need"] = 1,
["finished"] = true,
},
{
["type"] = "monster",
["have"] = 1,
["text_info"] = "present",
["text"] = "1/1 Speak with Cairne Bloodhoof",
["need"] = 1,
["finished"] = true,
},
{
["type"] = "monster",
["have"] = 1,
["text_info"] = "present",
["text"] = "1/1 Speak with Lady Sylvanas Windrunner",
["need"] = 1,
["finished"] = true,
},
},
["source"] = "C_QuestLog.GetQuestObjectives",
["log_index"] = 2,
["complete"] = true,
["ready"] = true,
},
[98024] = {
["title"] = "Journey to the Crossroads",
["objectives"] = {
},
["source"] = "C_QuestLog.GetQuestObjectives",
["log_index"] = 6,
["complete"] = true,
["ready"] = true,
},
[92401] = {
["title"] = "A Frightened Request",
["objectives"] = {
{
["type"] = "event",
["have"] = 1,
["text_info"] = "present",
["text"] = "Investigate the disappearance of Edward Heartweaver in the Ruins of Lordaeron.",
["need"] = 1,
["finished"] = true,
},
},
["source"] = "C_QuestLog.GetQuestObjectives",
["log_index"] = 8,
["complete"] = true,
["ready"] = true,
},
},
["counts"] = {
["QUEST_LOG_UPDATE"] = 1,
},
["build"] = "70124",
},
{
["probe_version"] = "m8-9-probe-0.1",
["baseline"] = {
[1013] = {
["title"] = "The Book of Ur",
["ready"] = false,
["complete"] = false,
["log_index"] = 4,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "item",
["have"] = 0,
["text_info"] = "present",
["text"] = "0/1 The Book of Ur",
["need"] = 1,
["finished"] = false,
},
},
},
[93739] = {
["title"] = "Exploring the Horde",
["ready"] = true,
["complete"] = true,
["log_index"] = 2,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "monster",
["have"] = 1,
["text_info"] = "present",
["text"] = "1/1 Obtain Instructions from Nazgrel",
["need"] = 1,
["finished"] = true,
},
{
["type"] = "monster",
["have"] = 1,
["text_info"] = "present",
["text"] = "1/1 Speak with Vol'jin",
["need"] = 1,
["finished"] = true,
},
{
["type"] = "monster",
["have"] = 1,
["text_info"] = "present",
["text"] = "1/1 Speak with Cairne Bloodhoof",
["need"] = 1,
["finished"] = true,
},
{
["type"] = "monster",
["have"] = 1,
["text_info"] = "present",
["text"] = "1/1 Speak with Lady Sylvanas Windrunner",
["need"] = 1,
["finished"] = true,
},
},
},
[98024] = {
["title"] = "Journey to the Crossroads",
["ready"] = true,
["complete"] = true,
["log_index"] = 6,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
},
},
[92401] = {
["title"] = "A Frightened Request",
["ready"] = true,
["complete"] = true,
["log_index"] = 8,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "event",
["have"] = 1,
["text_info"] = "present",
["text"] = "Investigate the disappearance of Edward Heartweaver in the Ruins of Lordaeron.",
["need"] = 1,
["finished"] = true,
},
},
},
},
["final_t"] = 1171999.394,
["build_date"] = "Sep 29 2026",
["final_snapshot"] = {
[1013] = {
["title"] = "The Book of Ur",
["ready"] = false,
["complete"] = false,
["log_index"] = 3,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "item",
["have"] = 0,
["text_info"] = "present",
["text"] = "0/1 The Book of Ur",
["need"] = 1,
["finished"] = false,
},
},
},
[98024] = {
["title"] = "Journey to the Crossroads",
["ready"] = true,
["complete"] = true,
["log_index"] = 16,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
},
},
[429] = {
["title"] = "Wild Hearts",
["ready"] = false,
["complete"] = false,
["log_index"] = 7,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "item",
["have"] = 1,
["text_info"] = "present",
["text"] = "1/3 Discolored Worg Heart",
["need"] = 3,
["finished"] = false,
},
},
},
[447] = {
["title"] = "A Recipe For Death",
["ready"] = true,
["complete"] = true,
["log_index"] = 8,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "item",
["have"] = 6,
["text_info"] = "present",
["text"] = "6/6 Grizzled Bear Heart",
["need"] = 6,
["finished"] = true,
},
{
["type"] = "item",
["have"] = 6,
["text_info"] = "present",
["text"] = "6/6 Skittering Blood",
["need"] = 6,
["finished"] = true,
},
},
},
[1014] = {
["title"] = "Arugal Must Die",
["ready"] = false,
["complete"] = false,
["log_index"] = 4,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "item",
["have"] = 0,
["text_info"] = "present",
["text"] = "0/1 Head of Arugal",
["need"] = 1,
["finished"] = false,
},
},
},
[1098] = {
["title"] = "Deathstalkers in Shadowfang",
["ready"] = true,
["complete"] = true,
["log_index"] = 2,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
},
},
[93739] = {
["title"] = "Exploring the Horde",
["ready"] = true,
["complete"] = true,
["log_index"] = 14,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "monster",
["have"] = 1,
["text_info"] = "present",
["text"] = "1/1 Obtain Instructions from Nazgrel",
["need"] = 1,
["finished"] = true,
},
{
["type"] = "monster",
["have"] = 1,
["text_info"] = "present",
["text"] = "1/1 Speak with Vol'jin",
["need"] = 1,
["finished"] = true,
},
{
["type"] = "monster",
["have"] = 1,
["text_info"] = "present",
["text"] = "1/1 Speak with Cairne Bloodhoof",
["need"] = 1,
["finished"] = true,
},
{
["type"] = "monster",
["have"] = 1,
["text_info"] = "present",
["text"] = "1/1 Speak with Lady Sylvanas Windrunner",
["need"] = 1,
["finished"] = true,
},
},
},
[421] = {
["title"] = "Prove Your Worth",
["ready"] = false,
["complete"] = false,
["log_index"] = 6,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "monster",
["have"] = 0,
["text_info"] = "present",
["text"] = "0/5 Moonrage Whitescalp slain",
["need"] = 5,
["finished"] = false,
},
},
},
[437] = {
["title"] = "The Dead Fields",
["ready"] = true,
["complete"] = true,
["log_index"] = 10,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "item",
["have"] = 1,
["text_info"] = "present",
["text"] = "1/1 Essence of Nightlash",
["need"] = 1,
["finished"] = true,
},
{
["type"] = "event",
["have"] = 1,
["text_info"] = "present",
["text"] = "Enter the Dead Fields",
["need"] = 1,
["finished"] = true,
},
},
},
[493] = {
["title"] = "Journey to Hillsbrad Foothills",
["ready"] = true,
["complete"] = true,
["log_index"] = 11,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "log",
["have"] = 1,
["text_info"] = "present",
["text"] = "Deliver Apothecary Renferrel's findings to Apothecary Lydon in the town of Tarren Mill in the Hillsbrad Foothills.",
["need"] = 1,
["finished"] = true,
},
},
},
[516] = {
["title"] = "Beren's Peril",
["ready"] = false,
["complete"] = false,
["log_index"] = 12,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "monster",
["have"] = 0,
["text_info"] = "present",
["text"] = "0/6 Ravenclaw Drudger slain",
["need"] = 6,
["finished"] = false,
},
{
["type"] = "monster",
["have"] = 0,
["text_info"] = "present",
["text"] = "0/6 Ravenclaw Guardian slain",
["need"] = 6,
["finished"] = false,
},
},
},
[477] = {
["title"] = "Border Crossings",
["ready"] = true,
["complete"] = true,
["log_index"] = 9,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
},
},
},
["registration"] = {
["UI_INFO_MESSAGE"] = "registered",
["QUEST_REMOVED"] = "registered",
["UNIT_QUEST_LOG_CHANGED"] = "registered",
["QUEST_ACCEPTED"] = "registered",
["QUEST_TURNED_IN"] = "registered",
["QUEST_WATCH_UPDATE"] = "registered",
["QUEST_LOG_UPDATE"] = "registered",
},
["toc_version"] = 16001,
["onupdate_install"] = "installed",
["records"] = {
{
["seq"] = 1,
["immediate_change_count"] = 0,
["args"] = {
["n"] = 0,
},
["t"] = 1170002.36,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
["pre_baseline"] = true,
},
{
["t"] = 1170239.21,
["changes"] = {
{
["quest_id"] = 92401,
["title"] = "A Frightened Request",
["from"] = true,
["kind"] = "complete_changed",
["to"] = false,
},
{
["quest_id"] = 92401,
["title"] = "A Frightened Request",
["from"] = true,
["kind"] = "ready_changed",
["to"] = false,
},
{
["quest_id"] = 92401,
["title"] = "A Frightened Request",
["from"] = {
["text"] = "Investigate the disappearance of Edward Heartweaver in the Ruins of Lordaeron.",
["finished"] = true,
["have"] = 1,
["need"] = 1,
},
["kind"] = "objective_changed",
["to"] = {
["text"] = "Investigate the disappearance of Edward Heartweaver in the Ruins of Lordaeron.",
["finished"] = false,
["have"] = 0,
["need"] = 1,
},
["index"] = 1,
},
},
["quest_snapshots"] = {
[92401] = {
["title"] = "A Frightened Request",
["ready"] = false,
["complete"] = false,
["log_index"] = 8,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "event",
["have"] = 0,
["text_info"] = "present",
["text"] = "Investigate the disappearance of Edward Heartweaver in the Ruins of Lordaeron.",
["need"] = 1,
["finished"] = false,
},
},
},
},
["meaningful"] = 3,
["seq"] = 2,
["seconds_after_trigger"] = 0,
["kind"] = "change",
["detected_by"] = "event",
["trigger_event"] = "UNIT_QUEST_LOG_CHANGED",
},
{
["seq"] = 3,
["immediate_change_count"] = 3,
["args"] = {
{
["value"] = "player",
["type"] = "string",
},
["n"] = 1,
},
["t"] = 1170239.21,
["kind"] = "event",
["event"] = "UNIT_QUEST_LOG_CHANGED",
},
{
["seq"] = 4,
["immediate_change_count"] = 0,
["args"] = {
["n"] = 0,
},
["t"] = 1170239.21,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["args"] = {
{
["value"] = 92401,
["type"] = "number",
},
{
["value"] = false,
["type"] = "boolean",
},
["n"] = 2,
},
["t"] = 1170239.21,
["kind"] = "context",
["event"] = "QUEST_REMOVED",
["seq"] = 5,
},
{
["args"] = {
{
["value"] = 92401,
["type"] = "number",
},
{
["value"] = 7050,
["type"] = "number",
},
{
["value"] = 0,
["type"] = "number",
},
["n"] = 3,
},
["t"] = 1170239.254,
["kind"] = "context",
["event"] = "QUEST_TURNED_IN",
["seq"] = 6,
},
{
["t"] = 1170239.254,
["changes"] = {
{
["quest_id"] = 92401,
["kind"] = "quest_removed",
["title"] = "A Frightened Request",
},
},
["quest_snapshots"] = {
},
["meaningful"] = 0,
["seq"] = 7,
["seconds_after_trigger"] = 0,
["kind"] = "change",
["detected_by"] = "event",
["trigger_event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 8,
["immediate_change_count"] = 1,
["args"] = {
["n"] = 0,
},
["t"] = 1170239.254,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 9,
["immediate_change_count"] = 0,
["args"] = {
{
["value"] = "player",
["type"] = "string",
},
["n"] = 1,
},
["t"] = 1170254.995,
["kind"] = "event",
["event"] = "UNIT_QUEST_LOG_CHANGED",
},
{
["args"] = {
{
["value"] = 477,
["type"] = "number",
},
["n"] = 1,
},
["t"] = 1170254.995,
["kind"] = "context",
["event"] = "QUEST_ACCEPTED",
["seq"] = 10,
},
{
["t"] = 1170255.012,
["changes"] = {
{
["quest_id"] = 477,
["kind"] = "quest_added",
["title"] = "Border Crossings",
},
},
["quest_snapshots"] = {
[477] = {
["title"] = "Border Crossings",
["ready"] = true,
["complete"] = true,
["log_index"] = 6,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
},
},
},
["meaningful"] = 0,
["seq"] = 11,
["seconds_after_trigger"] = 0,
["kind"] = "change",
["detected_by"] = "event",
["trigger_event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 12,
["immediate_change_count"] = 1,
["args"] = {
["n"] = 0,
},
["t"] = 1170255.012,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 13,
["immediate_change_count"] = 0,
["args"] = {
{
["value"] = "player",
["type"] = "string",
},
["n"] = 1,
},
["t"] = 1170256.263,
["kind"] = "event",
["event"] = "UNIT_QUEST_LOG_CHANGED",
},
{
["args"] = {
{
["value"] = 516,
["type"] = "number",
},
["n"] = 1,
},
["t"] = 1170256.263,
["kind"] = "context",
["event"] = "QUEST_ACCEPTED",
["seq"] = 14,
},
{
["t"] = 1170256.288,
["changes"] = {
{
["quest_id"] = 516,
["kind"] = "quest_added",
["title"] = "Beren's Peril",
},
},
["quest_snapshots"] = {
[516] = {
["title"] = "Beren's Peril",
["ready"] = false,
["complete"] = false,
["log_index"] = 7,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "monster",
["have"] = 0,
["text_info"] = "present",
["text"] = "0/6   slain",
["need"] = 6,
["finished"] = false,
},
{
["type"] = "monster",
["have"] = 0,
["text_info"] = "present",
["text"] = "0/6   slain",
["need"] = 6,
["finished"] = false,
},
},
},
},
["meaningful"] = 0,
["seq"] = 15,
["seconds_after_trigger"] = 0,
["kind"] = "change",
["detected_by"] = "event",
["trigger_event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 16,
["immediate_change_count"] = 1,
["args"] = {
["n"] = 0,
},
["t"] = 1170256.288,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["t"] = 1170256.506,
["changes"] = {
{
["quest_id"] = 516,
["title"] = "Beren's Peril",
["from"] = {
["text"] = "0/6   slain",
["finished"] = false,
["have"] = 0,
["need"] = 6,
},
["kind"] = "objective_changed",
["to"] = {
["text"] = "0/6 Ravenclaw Drudger slain",
["finished"] = false,
["have"] = 0,
["need"] = 6,
},
["index"] = 1,
},
{
["quest_id"] = 516,
["title"] = "Beren's Peril",
["from"] = {
["text"] = "0/6   slain",
["finished"] = false,
["have"] = 0,
["need"] = 6,
},
["kind"] = "objective_changed",
["to"] = {
["text"] = "0/6 Ravenclaw Guardian slain",
["finished"] = false,
["have"] = 0,
["need"] = 6,
},
["index"] = 2,
},
},
["quest_snapshots"] = {
[516] = {
["title"] = "Beren's Peril",
["ready"] = false,
["complete"] = false,
["log_index"] = 7,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "monster",
["have"] = 0,
["text_info"] = "present",
["text"] = "0/6 Ravenclaw Drudger slain",
["need"] = 6,
["finished"] = false,
},
{
["type"] = "monster",
["have"] = 0,
["text_info"] = "present",
["text"] = "0/6 Ravenclaw Guardian slain",
["need"] = 6,
["finished"] = false,
},
},
},
},
["meaningful"] = 2,
["seq"] = 17,
["seconds_after_trigger"] = 0,
["kind"] = "change",
["detected_by"] = "event",
["trigger_event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 18,
["immediate_change_count"] = 2,
["args"] = {
["n"] = 0,
},
["t"] = 1170256.506,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 19,
["immediate_change_count"] = 0,
["args"] = {
{
["value"] = "player",
["type"] = "string",
},
["n"] = 1,
},
["t"] = 1170265.199,
["kind"] = "event",
["event"] = "UNIT_QUEST_LOG_CHANGED",
},
{
["args"] = {
{
["value"] = 447,
["type"] = "number",
},
["n"] = 1,
},
["t"] = 1170265.199,
["kind"] = "context",
["event"] = "QUEST_ACCEPTED",
["seq"] = 20,
},
{
["t"] = 1170265.214,
["changes"] = {
{
["quest_id"] = 447,
["kind"] = "quest_added",
["title"] = "A Recipe For Death",
},
},
["quest_snapshots"] = {
[447] = {
["title"] = "A Recipe For Death",
["ready"] = false,
["complete"] = false,
["log_index"] = 6,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "item",
["have"] = 0,
["text_info"] = "count_only_no_name",
["text"] = "0/6  ",
["need"] = 6,
["finished"] = false,
},
{
["type"] = "item",
["have"] = 0,
["text_info"] = "count_only_no_name",
["text"] = "0/6  ",
["need"] = 6,
["finished"] = false,
},
},
},
},
["meaningful"] = 0,
["seq"] = 21,
["seconds_after_trigger"] = 0,
["kind"] = "change",
["detected_by"] = "event",
["trigger_event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 22,
["immediate_change_count"] = 1,
["args"] = {
["n"] = 0,
},
["t"] = 1170265.214,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["t"] = 1170265.231,
["changes"] = {
{
["quest_id"] = 447,
["title"] = "A Recipe For Death",
["from"] = {
["text"] = "0/6  ",
["finished"] = false,
["have"] = 0,
["need"] = 6,
},
["kind"] = "objective_changed",
["to"] = {
["text"] = "0/6 Grizzled Bear Heart",
["finished"] = false,
["have"] = 0,
["need"] = 6,
},
["index"] = 1,
},
{
["quest_id"] = 447,
["title"] = "A Recipe For Death",
["from"] = {
["text"] = "0/6  ",
["finished"] = false,
["have"] = 0,
["need"] = 6,
},
["kind"] = "objective_changed",
["to"] = {
["text"] = "0/6 Skittering Blood",
["finished"] = false,
["have"] = 0,
["need"] = 6,
},
["index"] = 2,
},
},
["quest_snapshots"] = {
[447] = {
["title"] = "A Recipe For Death",
["ready"] = false,
["complete"] = false,
["log_index"] = 6,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "item",
["have"] = 0,
["text_info"] = "present",
["text"] = "0/6 Grizzled Bear Heart",
["need"] = 6,
["finished"] = false,
},
{
["type"] = "item",
["have"] = 0,
["text_info"] = "present",
["text"] = "0/6 Skittering Blood",
["need"] = 6,
["finished"] = false,
},
},
},
},
["meaningful"] = 2,
["seq"] = 23,
["seconds_after_trigger"] = 0,
["kind"] = "change",
["detected_by"] = "event",
["trigger_event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 24,
["immediate_change_count"] = 2,
["args"] = {
["n"] = 0,
},
["t"] = 1170265.231,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 25,
["immediate_change_count"] = 0,
["args"] = {
{
["value"] = "player",
["type"] = "string",
},
["n"] = 1,
},
["t"] = 1170266.695,
["kind"] = "event",
["event"] = "UNIT_QUEST_LOG_CHANGED",
},
{
["args"] = {
{
["value"] = 314,
["type"] = "number",
},
{
["value"] = "Objective Complete.",
["type"] = "string",
},
["n"] = 2,
},
["t"] = 1170266.695,
["kind"] = "context",
["event"] = "UI_INFO_MESSAGE",
["seq"] = 26,
},
{
["args"] = {
{
["value"] = 493,
["type"] = "number",
},
["n"] = 1,
},
["t"] = 1170266.695,
["kind"] = "context",
["event"] = "QUEST_ACCEPTED",
["seq"] = 27,
},
{
["t"] = 1170266.721,
["changes"] = {
{
["quest_id"] = 493,
["kind"] = "quest_added",
["title"] = "Journey to Hillsbrad Foothills",
},
},
["quest_snapshots"] = {
[493] = {
["title"] = "Journey to Hillsbrad Foothills",
["ready"] = true,
["complete"] = true,
["log_index"] = 8,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "log",
["have"] = 1,
["text_info"] = "present",
["text"] = "Deliver Apothecary Renferrel's findings to Apothecary Lydon in the town of Tarren Mill in the Hillsbrad Foothills.",
["need"] = 1,
["finished"] = true,
},
},
},
},
["meaningful"] = 0,
["seq"] = 28,
["seconds_after_trigger"] = 0,
["kind"] = "change",
["detected_by"] = "event",
["trigger_event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 29,
["immediate_change_count"] = 1,
["args"] = {
["n"] = 0,
},
["t"] = 1170266.721,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 30,
["immediate_change_count"] = 0,
["t"] = 1170266.721,
["args"] = {
{
["value"] = 493,
["type"] = "number",
},
["n"] = 1,
},
["arg1_resolved"] = {
["value"] = 493,
["title_if_quest_id"] = "Journey to Hillsbrad Foothills",
},
["kind"] = "event",
["event"] = "QUEST_WATCH_UPDATE",
},
{
["args"] = {
{
["value"] = 317,
["type"] = "number",
},
{
["value"] = "Renferrel's Findings: 1/1",
["type"] = "string",
},
["n"] = 2,
},
["t"] = 1170266.737,
["kind"] = "context",
["event"] = "UI_INFO_MESSAGE",
["seq"] = 31,
},
{
["seq"] = 32,
["immediate_change_count"] = 0,
["args"] = {
["n"] = 0,
},
["t"] = 1170267.14,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 33,
["immediate_change_count"] = 0,
["args"] = {
{
["value"] = "player",
["type"] = "string",
},
["n"] = 1,
},
["t"] = 1170291.485,
["kind"] = "event",
["event"] = "UNIT_QUEST_LOG_CHANGED",
},
{
["args"] = {
{
["value"] = 428,
["type"] = "number",
},
["n"] = 1,
},
["t"] = 1170291.485,
["kind"] = "context",
["event"] = "QUEST_ACCEPTED",
["seq"] = 34,
},
{
["t"] = 1170291.492,
["changes"] = {
{
["quest_id"] = 428,
["kind"] = "quest_added",
["title"] = "Lost Deathstalkers",
},
},
["quest_snapshots"] = {
[428] = {
["title"] = "Lost Deathstalkers",
["ready"] = true,
["complete"] = true,
["log_index"] = 7,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
},
},
},
["meaningful"] = 0,
["seq"] = 35,
["seconds_after_trigger"] = 0,
["kind"] = "change",
["detected_by"] = "event",
["trigger_event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 36,
["immediate_change_count"] = 1,
["args"] = {
["n"] = 0,
},
["t"] = 1170291.492,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 37,
["immediate_change_count"] = 0,
["args"] = {
{
["value"] = "player",
["type"] = "string",
},
["n"] = 1,
},
["t"] = 1170292.674,
["kind"] = "event",
["event"] = "UNIT_QUEST_LOG_CHANGED",
},
{
["args"] = {
{
["value"] = 437,
["type"] = "number",
},
["n"] = 1,
},
["t"] = 1170292.674,
["kind"] = "context",
["event"] = "QUEST_ACCEPTED",
["seq"] = 38,
},
{
["t"] = 1170292.681,
["changes"] = {
{
["quest_id"] = 437,
["kind"] = "quest_added",
["title"] = "The Dead Fields",
},
},
["quest_snapshots"] = {
[437] = {
["title"] = "The Dead Fields",
["ready"] = false,
["complete"] = false,
["log_index"] = 9,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "item",
["have"] = 0,
["text_info"] = "count_only_no_name",
["text"] = "0/1  ",
["need"] = 1,
["finished"] = false,
},
{
["type"] = "event",
["have"] = 0,
["text_info"] = "present",
["text"] = "Enter the Dead Fields",
["need"] = 1,
["finished"] = false,
},
},
},
},
["meaningful"] = 0,
["seq"] = 39,
["seconds_after_trigger"] = 0,
["kind"] = "change",
["detected_by"] = "event",
["trigger_event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 40,
["immediate_change_count"] = 1,
["args"] = {
["n"] = 0,
},
["t"] = 1170292.681,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["t"] = 1170292.701,
["changes"] = {
{
["quest_id"] = 437,
["title"] = "The Dead Fields",
["from"] = {
["text"] = "0/1  ",
["finished"] = false,
["have"] = 0,
["need"] = 1,
},
["kind"] = "objective_changed",
["to"] = {
["text"] = "0/1 Essence of Nightlash",
["finished"] = false,
["have"] = 0,
["need"] = 1,
},
["index"] = 1,
},
},
["quest_snapshots"] = {
[437] = {
["title"] = "The Dead Fields",
["ready"] = false,
["complete"] = false,
["log_index"] = 9,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "item",
["have"] = 0,
["text_info"] = "present",
["text"] = "0/1 Essence of Nightlash",
["need"] = 1,
["finished"] = false,
},
{
["type"] = "event",
["have"] = 0,
["text_info"] = "present",
["text"] = "Enter the Dead Fields",
["need"] = 1,
["finished"] = false,
},
},
},
},
["meaningful"] = 1,
["seq"] = 41,
["seconds_after_trigger"] = 0,
["kind"] = "change",
["detected_by"] = "event",
["trigger_event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 42,
["immediate_change_count"] = 1,
["args"] = {
["n"] = 0,
},
["t"] = 1170292.701,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 43,
["immediate_change_count"] = 0,
["args"] = {
{
["value"] = "player",
["type"] = "string",
},
["n"] = 1,
},
["t"] = 1170297.562,
["kind"] = "event",
["event"] = "UNIT_QUEST_LOG_CHANGED",
},
{
["args"] = {
{
["value"] = 1098,
["type"] = "number",
},
["n"] = 1,
},
["t"] = 1170297.562,
["kind"] = "context",
["event"] = "QUEST_ACCEPTED",
["seq"] = 44,
},
{
["t"] = 1170297.569,
["changes"] = {
{
["quest_id"] = 1098,
["kind"] = "quest_added",
["title"] = "Deathstalkers in Shadowfang",
},
},
["quest_snapshots"] = {
[1098] = {
["title"] = "Deathstalkers in Shadowfang",
["ready"] = true,
["complete"] = true,
["log_index"] = 4,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
},
},
},
["meaningful"] = 0,
["seq"] = 45,
["seconds_after_trigger"] = 0,
["kind"] = "change",
["detected_by"] = "event",
["trigger_event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 46,
["immediate_change_count"] = 1,
["args"] = {
["n"] = 0,
},
["t"] = 1170297.569,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 47,
["immediate_change_count"] = 0,
["args"] = {
{
["value"] = "player",
["type"] = "string",
},
["n"] = 1,
},
["t"] = 1170317.767,
["kind"] = "event",
["event"] = "UNIT_QUEST_LOG_CHANGED",
},
{
["args"] = {
{
["value"] = 421,
["type"] = "number",
},
["n"] = 1,
},
["t"] = 1170317.767,
["kind"] = "context",
["event"] = "QUEST_ACCEPTED",
["seq"] = 48,
},
{
["t"] = 1170317.776,
["changes"] = {
{
["quest_id"] = 421,
["kind"] = "quest_added",
["title"] = "Prove Your Worth",
},
},
["quest_snapshots"] = {
[421] = {
["title"] = "Prove Your Worth",
["ready"] = false,
["complete"] = false,
["log_index"] = 7,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "monster",
["have"] = 0,
["text_info"] = "present",
["text"] = "0/5   slain",
["need"] = 5,
["finished"] = false,
},
},
},
},
["meaningful"] = 0,
["seq"] = 49,
["seconds_after_trigger"] = 0,
["kind"] = "change",
["detected_by"] = "event",
["trigger_event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 50,
["immediate_change_count"] = 1,
["args"] = {
["n"] = 0,
},
["t"] = 1170317.776,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["t"] = 1170317.891,
["changes"] = {
{
["quest_id"] = 421,
["title"] = "Prove Your Worth",
["from"] = {
["text"] = "0/5   slain",
["finished"] = false,
["have"] = 0,
["need"] = 5,
},
["kind"] = "objective_changed",
["to"] = {
["text"] = "0/5 Moonrage Whitescalp slain",
["finished"] = false,
["have"] = 0,
["need"] = 5,
},
["index"] = 1,
},
},
["quest_snapshots"] = {
[421] = {
["title"] = "Prove Your Worth",
["ready"] = false,
["complete"] = false,
["log_index"] = 7,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "monster",
["have"] = 0,
["text_info"] = "present",
["text"] = "0/5 Moonrage Whitescalp slain",
["need"] = 5,
["finished"] = false,
},
},
},
},
["meaningful"] = 1,
["seq"] = 51,
["seconds_after_trigger"] = 0,
["kind"] = "change",
["detected_by"] = "event",
["trigger_event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 52,
["immediate_change_count"] = 1,
["args"] = {
["n"] = 0,
},
["t"] = 1170317.891,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 53,
["immediate_change_count"] = 0,
["args"] = {
{
["value"] = "player",
["type"] = "string",
},
["n"] = 1,
},
["t"] = 1170319.792,
["kind"] = "event",
["event"] = "UNIT_QUEST_LOG_CHANGED",
},
{
["args"] = {
{
["value"] = 1014,
["type"] = "number",
},
["n"] = 1,
},
["t"] = 1170319.792,
["kind"] = "context",
["event"] = "QUEST_ACCEPTED",
["seq"] = 54,
},
{
["t"] = 1170319.799,
["changes"] = {
{
["quest_id"] = 1014,
["kind"] = "quest_added",
["title"] = "Arugal Must Die",
},
},
["quest_snapshots"] = {
[1014] = {
["title"] = "Arugal Must Die",
["ready"] = false,
["complete"] = false,
["log_index"] = 6,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "item",
["have"] = 0,
["text_info"] = "count_only_no_name",
["text"] = "0/1  ",
["need"] = 1,
["finished"] = false,
},
},
},
},
["meaningful"] = 0,
["seq"] = 55,
["seconds_after_trigger"] = 0,
["kind"] = "change",
["detected_by"] = "event",
["trigger_event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 56,
["immediate_change_count"] = 1,
["args"] = {
["n"] = 0,
},
["t"] = 1170319.799,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["t"] = 1170319.818,
["changes"] = {
{
["quest_id"] = 1014,
["title"] = "Arugal Must Die",
["from"] = {
["text"] = "0/1  ",
["finished"] = false,
["have"] = 0,
["need"] = 1,
},
["kind"] = "objective_changed",
["to"] = {
["text"] = "0/1 Head of Arugal",
["finished"] = false,
["have"] = 0,
["need"] = 1,
},
["index"] = 1,
},
},
["quest_snapshots"] = {
[1014] = {
["title"] = "Arugal Must Die",
["ready"] = false,
["complete"] = false,
["log_index"] = 6,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "item",
["have"] = 0,
["text_info"] = "present",
["text"] = "0/1 Head of Arugal",
["need"] = 1,
["finished"] = false,
},
},
},
},
["meaningful"] = 1,
["seq"] = 57,
["seconds_after_trigger"] = 0,
["kind"] = "change",
["detected_by"] = "event",
["trigger_event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 58,
["immediate_change_count"] = 1,
["args"] = {
["n"] = 0,
},
["t"] = 1170319.818,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 59,
["immediate_change_count"] = 0,
["args"] = {
["n"] = 0,
},
["t"] = 1170321.765,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["t"] = 1170344.4,
["kind"] = "manual_snapshot",
["seq"] = 60,
["snapshot"] = {
[1013] = {
["title"] = "The Book of Ur",
["ready"] = false,
["complete"] = false,
["log_index"] = 3,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "item",
["have"] = 0,
["text_info"] = "present",
["text"] = "0/1 The Book of Ur",
["need"] = 1,
["finished"] = false,
},
},
},
[98024] = {
["title"] = "Journey to the Crossroads",
["ready"] = true,
["complete"] = true,
["log_index"] = 16,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
},
},
[428] = {
["title"] = "Lost Deathstalkers",
["ready"] = true,
["complete"] = true,
["log_index"] = 8,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
},
},
[447] = {
["title"] = "A Recipe For Death",
["ready"] = false,
["complete"] = false,
["log_index"] = 7,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "item",
["have"] = 0,
["text_info"] = "present",
["text"] = "0/6 Grizzled Bear Heart",
["need"] = 6,
["finished"] = false,
},
{
["type"] = "item",
["have"] = 0,
["text_info"] = "present",
["text"] = "0/6 Skittering Blood",
["need"] = 6,
["finished"] = false,
},
},
},
[1014] = {
["title"] = "Arugal Must Die",
["ready"] = false,
["complete"] = false,
["log_index"] = 4,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "item",
["have"] = 0,
["text_info"] = "present",
["text"] = "0/1 Head of Arugal",
["need"] = 1,
["finished"] = false,
},
},
},
[1098] = {
["title"] = "Deathstalkers in Shadowfang",
["ready"] = true,
["complete"] = true,
["log_index"] = 2,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
},
},
[93739] = {
["title"] = "Exploring the Horde",
["ready"] = true,
["complete"] = true,
["log_index"] = 14,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "monster",
["have"] = 1,
["text_info"] = "present",
["text"] = "1/1 Obtain Instructions from Nazgrel",
["need"] = 1,
["finished"] = true,
},
{
["type"] = "monster",
["have"] = 1,
["text_info"] = "present",
["text"] = "1/1 Speak with Vol'jin",
["need"] = 1,
["finished"] = true,
},
{
["type"] = "monster",
["have"] = 1,
["text_info"] = "present",
["text"] = "1/1 Speak with Cairne Bloodhoof",
["need"] = 1,
["finished"] = true,
},
{
["type"] = "monster",
["have"] = 1,
["text_info"] = "present",
["text"] = "1/1 Speak with Lady Sylvanas Windrunner",
["need"] = 1,
["finished"] = true,
},
},
},
[421] = {
["title"] = "Prove Your Worth",
["ready"] = false,
["complete"] = false,
["log_index"] = 6,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "monster",
["have"] = 0,
["text_info"] = "present",
["text"] = "0/5 Moonrage Whitescalp slain",
["need"] = 5,
["finished"] = false,
},
},
},
[437] = {
["title"] = "The Dead Fields",
["ready"] = false,
["complete"] = false,
["log_index"] = 10,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "item",
["have"] = 0,
["text_info"] = "present",
["text"] = "0/1 Essence of Nightlash",
["need"] = 1,
["finished"] = false,
},
{
["type"] = "event",
["have"] = 0,
["text_info"] = "present",
["text"] = "Enter the Dead Fields",
["need"] = 1,
["finished"] = false,
},
},
},
[493] = {
["title"] = "Journey to Hillsbrad Foothills",
["ready"] = true,
["complete"] = true,
["log_index"] = 11,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "log",
["have"] = 1,
["text_info"] = "present",
["text"] = "Deliver Apothecary Renferrel's findings to Apothecary Lydon in the town of Tarren Mill in the Hillsbrad Foothills.",
["need"] = 1,
["finished"] = true,
},
},
},
[516] = {
["title"] = "Beren's Peril",
["ready"] = false,
["complete"] = false,
["log_index"] = 12,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "monster",
["have"] = 0,
["text_info"] = "present",
["text"] = "0/6 Ravenclaw Drudger slain",
["need"] = 6,
["finished"] = false,
},
{
["type"] = "monster",
["have"] = 0,
["text_info"] = "present",
["text"] = "0/6 Ravenclaw Guardian slain",
["need"] = 6,
["finished"] = false,
},
},
},
[477] = {
["title"] = "Border Crossings",
["ready"] = true,
["complete"] = true,
["log_index"] = 9,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
},
},
},
},
{
["seq"] = 61,
["immediate_change_count"] = 0,
["args"] = {
["n"] = 0,
},
["t"] = 1170368.318,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 62,
["immediate_change_count"] = 0,
["args"] = {
["n"] = 0,
},
["t"] = 1170410.923,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 63,
["immediate_change_count"] = 0,
["t"] = 1170480.621,
["args"] = {
{
["value"] = 447,
["type"] = "number",
},
["n"] = 1,
},
["arg1_resolved"] = {
["value"] = 447,
["title_if_quest_id"] = "A Recipe For Death",
},
["kind"] = "event",
["event"] = "QUEST_WATCH_UPDATE",
},
{
["args"] = {
{
["value"] = 317,
["type"] = "number",
},
{
["value"] = "Grizzled Bear Heart: 1/6",
["type"] = "string",
},
["n"] = 2,
},
["t"] = 1170480.621,
["kind"] = "context",
["event"] = "UI_INFO_MESSAGE",
["seq"] = 64,
},
{
["t"] = 1170480.73,
["changes"] = {
{
["quest_id"] = 447,
["title"] = "A Recipe For Death",
["from"] = {
["text"] = "0/6 Grizzled Bear Heart",
["finished"] = false,
["have"] = 0,
["need"] = 6,
},
["kind"] = "objective_changed",
["to"] = {
["text"] = "1/6 Grizzled Bear Heart",
["finished"] = false,
["have"] = 1,
["need"] = 6,
},
["index"] = 1,
},
},
["quest_snapshots"] = {
[447] = {
["title"] = "A Recipe For Death",
["ready"] = false,
["complete"] = false,
["log_index"] = 7,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "item",
["have"] = 1,
["text_info"] = "present",
["text"] = "1/6 Grizzled Bear Heart",
["need"] = 6,
["finished"] = false,
},
{
["type"] = "item",
["have"] = 0,
["text_info"] = "present",
["text"] = "0/6 Skittering Blood",
["need"] = 6,
["finished"] = false,
},
},
},
},
["meaningful"] = 1,
["seq"] = 65,
["seconds_after_trigger"] = 0,
["kind"] = "change",
["detected_by"] = "event",
["trigger_event"] = "UNIT_QUEST_LOG_CHANGED",
},
{
["seq"] = 66,
["immediate_change_count"] = 1,
["args"] = {
{
["value"] = "player",
["type"] = "string",
},
["n"] = 1,
},
["t"] = 1170480.73,
["kind"] = "event",
["event"] = "UNIT_QUEST_LOG_CHANGED",
},
{
["seq"] = 67,
["immediate_change_count"] = 0,
["args"] = {
["n"] = 0,
},
["t"] = 1170480.742,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 68,
["immediate_change_count"] = 0,
["args"] = {
["n"] = 0,
},
["t"] = 1170481.58,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 69,
["immediate_change_count"] = 0,
["t"] = 1170522.04,
["args"] = {
{
["value"] = 447,
["type"] = "number",
},
["n"] = 1,
},
["arg1_resolved"] = {
["value"] = 447,
["title_if_quest_id"] = "A Recipe For Death",
},
["kind"] = "event",
["event"] = "QUEST_WATCH_UPDATE",
},
{
["args"] = {
{
["value"] = 317,
["type"] = "number",
},
{
["value"] = "Grizzled Bear Heart: 2/6",
["type"] = "string",
},
["n"] = 2,
},
["t"] = 1170522.04,
["kind"] = "context",
["event"] = "UI_INFO_MESSAGE",
["seq"] = 70,
},
{
["t"] = 1170522.176,
["changes"] = {
{
["quest_id"] = 447,
["title"] = "A Recipe For Death",
["from"] = {
["text"] = "1/6 Grizzled Bear Heart",
["finished"] = false,
["have"] = 1,
["need"] = 6,
},
["kind"] = "objective_changed",
["to"] = {
["text"] = "2/6 Grizzled Bear Heart",
["finished"] = false,
["have"] = 2,
["need"] = 6,
},
["index"] = 1,
},
},
["quest_snapshots"] = {
[447] = {
["title"] = "A Recipe For Death",
["ready"] = false,
["complete"] = false,
["log_index"] = 9,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "item",
["have"] = 2,
["text_info"] = "present",
["text"] = "2/6 Grizzled Bear Heart",
["need"] = 6,
["finished"] = false,
},
{
["type"] = "item",
["have"] = 0,
["text_info"] = "present",
["text"] = "0/6 Skittering Blood",
["need"] = 6,
["finished"] = false,
},
},
},
},
["meaningful"] = 1,
["seq"] = 71,
["seconds_after_trigger"] = 0,
["kind"] = "change",
["detected_by"] = "event",
["trigger_event"] = "UNIT_QUEST_LOG_CHANGED",
},
{
["seq"] = 72,
["immediate_change_count"] = 1,
["args"] = {
{
["value"] = "player",
["type"] = "string",
},
["n"] = 1,
},
["t"] = 1170522.176,
["kind"] = "event",
["event"] = "UNIT_QUEST_LOG_CHANGED",
},
{
["seq"] = 73,
["immediate_change_count"] = 0,
["args"] = {
["n"] = 0,
},
["t"] = 1170522.183,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 74,
["immediate_change_count"] = 0,
["args"] = {
["n"] = 0,
},
["t"] = 1170522.329,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 75,
["immediate_change_count"] = 0,
["t"] = 1170522.857,
["args"] = {
{
["value"] = 447,
["type"] = "number",
},
["n"] = 1,
},
["arg1_resolved"] = {
["value"] = 447,
["title_if_quest_id"] = "A Recipe For Death",
},
["kind"] = "event",
["event"] = "QUEST_WATCH_UPDATE",
},
{
["args"] = {
{
["value"] = 317,
["type"] = "number",
},
{
["value"] = "Grizzled Bear Heart: 3/6",
["type"] = "string",
},
["n"] = 2,
},
["t"] = 1170522.857,
["kind"] = "context",
["event"] = "UI_INFO_MESSAGE",
["seq"] = 76,
},
{
["t"] = 1170522.97,
["changes"] = {
{
["quest_id"] = 447,
["title"] = "A Recipe For Death",
["from"] = {
["text"] = "2/6 Grizzled Bear Heart",
["finished"] = false,
["have"] = 2,
["need"] = 6,
},
["kind"] = "objective_changed",
["to"] = {
["text"] = "3/6 Grizzled Bear Heart",
["finished"] = false,
["have"] = 3,
["need"] = 6,
},
["index"] = 1,
},
},
["quest_snapshots"] = {
[447] = {
["title"] = "A Recipe For Death",
["ready"] = false,
["complete"] = false,
["log_index"] = 9,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "item",
["have"] = 3,
["text_info"] = "present",
["text"] = "3/6 Grizzled Bear Heart",
["need"] = 6,
["finished"] = false,
},
{
["type"] = "item",
["have"] = 0,
["text_info"] = "present",
["text"] = "0/6 Skittering Blood",
["need"] = 6,
["finished"] = false,
},
},
},
},
["meaningful"] = 1,
["seq"] = 77,
["seconds_after_trigger"] = 0,
["kind"] = "change",
["detected_by"] = "event",
["trigger_event"] = "UNIT_QUEST_LOG_CHANGED",
},
{
["seq"] = 78,
["immediate_change_count"] = 1,
["args"] = {
{
["value"] = "player",
["type"] = "string",
},
["n"] = 1,
},
["t"] = 1170522.97,
["kind"] = "event",
["event"] = "UNIT_QUEST_LOG_CHANGED",
},
{
["seq"] = 79,
["immediate_change_count"] = 0,
["args"] = {
["n"] = 0,
},
["t"] = 1170522.981,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 80,
["immediate_change_count"] = 0,
["args"] = {
["n"] = 0,
},
["t"] = 1170523.137,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 81,
["immediate_change_count"] = 0,
["args"] = {
["n"] = 0,
},
["t"] = 1170537.008,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["args"] = {
{
["value"] = 412,
["type"] = "number",
},
{
["value"] = "Discovered: The Ivar Patch",
["type"] = "string",
},
["n"] = 2,
},
["t"] = 1170545.672,
["kind"] = "context",
["event"] = "UI_INFO_MESSAGE",
["seq"] = 82,
},
{
["seq"] = 83,
["immediate_change_count"] = 0,
["args"] = {
["n"] = 0,
},
["t"] = 1170572.779,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["args"] = {
{
["value"] = 428,
["type"] = "number",
},
{
["value"] = 140,
["type"] = "number",
},
{
["value"] = 0,
["type"] = "number",
},
["n"] = 3,
},
["t"] = 1170572.788,
["kind"] = "context",
["event"] = "QUEST_TURNED_IN",
["seq"] = 84,
},
{
["t"] = 1170572.863,
["changes"] = {
{
["quest_id"] = 428,
["title"] = "Lost Deathstalkers",
["from"] = true,
["kind"] = "complete_changed",
["to"] = false,
},
},
["quest_snapshots"] = {
[428] = {
["title"] = "Lost Deathstalkers",
["ready"] = true,
["complete"] = false,
["log_index"] = 10,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
},
},
},
["meaningful"] = 1,
["seq"] = 85,
["seconds_after_trigger"] = 0,
["kind"] = "change",
["detected_by"] = "event",
["trigger_event"] = "UNIT_QUEST_LOG_CHANGED",
},
{
["seq"] = 86,
["immediate_change_count"] = 1,
["args"] = {
{
["value"] = "player",
["type"] = "string",
},
["n"] = 1,
},
["t"] = 1170572.863,
["kind"] = "event",
["event"] = "UNIT_QUEST_LOG_CHANGED",
},
{
["seq"] = 87,
["immediate_change_count"] = 0,
["args"] = {
["n"] = 0,
},
["t"] = 1170572.863,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["args"] = {
{
["value"] = 428,
["type"] = "number",
},
{
["value"] = false,
["type"] = "boolean",
},
["n"] = 2,
},
["t"] = 1170572.863,
["kind"] = "context",
["event"] = "QUEST_REMOVED",
["seq"] = 88,
},
{
["t"] = 1170572.875,
["changes"] = {
{
["quest_id"] = 428,
["kind"] = "quest_removed",
["title"] = "Lost Deathstalkers",
},
},
["quest_snapshots"] = {
},
["meaningful"] = 0,
["seq"] = 89,
["seconds_after_trigger"] = 0,
["kind"] = "change",
["detected_by"] = "event",
["trigger_event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 90,
["immediate_change_count"] = 1,
["args"] = {
["n"] = 0,
},
["t"] = 1170572.875,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 91,
["immediate_change_count"] = 0,
["args"] = {
["n"] = 0,
},
["t"] = 1170573.21,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 92,
["immediate_change_count"] = 0,
["args"] = {
{
["value"] = "player",
["type"] = "string",
},
["n"] = 1,
},
["t"] = 1170577.749,
["kind"] = "event",
["event"] = "UNIT_QUEST_LOG_CHANGED",
},
{
["args"] = {
{
["value"] = 429,
["type"] = "number",
},
["n"] = 1,
},
["t"] = 1170577.749,
["kind"] = "context",
["event"] = "QUEST_ACCEPTED",
["seq"] = 93,
},
{
["t"] = 1170577.757,
["changes"] = {
{
["quest_id"] = 429,
["kind"] = "quest_added",
["title"] = "Wild Hearts",
},
},
["quest_snapshots"] = {
[429] = {
["title"] = "Wild Hearts",
["ready"] = false,
["complete"] = false,
["log_index"] = 9,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "item",
["have"] = 0,
["text_info"] = "count_only_no_name",
["text"] = "0/3  ",
["need"] = 3,
["finished"] = false,
},
},
},
},
["meaningful"] = 0,
["seq"] = 94,
["seconds_after_trigger"] = 0,
["kind"] = "change",
["detected_by"] = "event",
["trigger_event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 95,
["immediate_change_count"] = 1,
["args"] = {
["n"] = 0,
},
["t"] = 1170577.757,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["t"] = 1170577.777,
["changes"] = {
{
["quest_id"] = 429,
["title"] = "Wild Hearts",
["from"] = {
["text"] = "0/3  ",
["finished"] = false,
["have"] = 0,
["need"] = 3,
},
["kind"] = "objective_changed",
["to"] = {
["text"] = "0/3 Discolored Worg Heart",
["finished"] = false,
["have"] = 0,
["need"] = 3,
},
["index"] = 1,
},
},
["quest_snapshots"] = {
[429] = {
["title"] = "Wild Hearts",
["ready"] = false,
["complete"] = false,
["log_index"] = 9,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "item",
["have"] = 0,
["text_info"] = "present",
["text"] = "0/3 Discolored Worg Heart",
["need"] = 3,
["finished"] = false,
},
},
},
},
["meaningful"] = 1,
["seq"] = 96,
["seconds_after_trigger"] = 0,
["kind"] = "change",
["detected_by"] = "event",
["trigger_event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 97,
["immediate_change_count"] = 1,
["args"] = {
["n"] = 0,
},
["t"] = 1170577.777,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 98,
["immediate_change_count"] = 0,
["args"] = {
["n"] = 0,
},
["t"] = 1170586.484,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["args"] = {
{
["value"] = 412,
["type"] = "number",
},
{
["value"] = "Discovered: The Dead Field",
["type"] = "string",
},
["n"] = 2,
},
["t"] = 1170688.686,
["kind"] = "context",
["event"] = "UI_INFO_MESSAGE",
["seq"] = 99,
},
{
["t"] = 1170726.384,
["changes"] = {
{
["quest_id"] = 437,
["title"] = "The Dead Fields",
["from"] = {
["text"] = "Enter the Dead Fields",
["finished"] = false,
["have"] = 0,
["need"] = 1,
},
["kind"] = "objective_changed",
["to"] = {
["text"] = "Enter the Dead Fields",
["finished"] = true,
["have"] = 1,
["need"] = 1,
},
["index"] = 2,
},
},
["quest_snapshots"] = {
[437] = {
["title"] = "The Dead Fields",
["ready"] = false,
["complete"] = false,
["log_index"] = 10,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "item",
["have"] = 0,
["text_info"] = "present",
["text"] = "0/1 Essence of Nightlash",
["need"] = 1,
["finished"] = false,
},
{
["type"] = "event",
["have"] = 1,
["text_info"] = "present",
["text"] = "Enter the Dead Fields",
["need"] = 1,
["finished"] = true,
},
},
},
},
["meaningful"] = 1,
["seq"] = 100,
["seconds_after_trigger"] = 0,
["kind"] = "change",
["detected_by"] = "event",
["trigger_event"] = "UNIT_QUEST_LOG_CHANGED",
},
{
["seq"] = 101,
["immediate_change_count"] = 1,
["args"] = {
{
["value"] = "player",
["type"] = "string",
},
["n"] = 1,
},
["t"] = 1170726.384,
["kind"] = "event",
["event"] = "UNIT_QUEST_LOG_CHANGED",
},
{
["seq"] = 102,
["immediate_change_count"] = 0,
["args"] = {
["n"] = 0,
},
["t"] = 1170726.392,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 103,
["immediate_change_count"] = 0,
["t"] = 1170743.689,
["args"] = {
{
["value"] = 437,
["type"] = "number",
},
["n"] = 1,
},
["arg1_resolved"] = {
["value"] = 437,
["title_if_quest_id"] = "The Dead Fields",
},
["kind"] = "event",
["event"] = "QUEST_WATCH_UPDATE",
},
{
["seq"] = 104,
["immediate_change_count"] = 0,
["t"] = 1170743.689,
["args"] = {
{
["value"] = 437,
["type"] = "number",
},
["n"] = 1,
},
["arg1_resolved"] = {
["value"] = 437,
["title_if_quest_id"] = "The Dead Fields",
},
["kind"] = "event",
["event"] = "QUEST_WATCH_UPDATE",
},
{
["args"] = {
{
["value"] = 317,
["type"] = "number",
},
{
["value"] = "Essence of Nightlash: 1/1",
["type"] = "string",
},
["n"] = 2,
},
["t"] = 1170743.689,
["kind"] = "context",
["event"] = "UI_INFO_MESSAGE",
["seq"] = 105,
},
{
["args"] = {
{
["value"] = 313,
["type"] = "number",
},
{
["value"] = "Enter the Dead Fields (Complete)",
["type"] = "string",
},
["n"] = 2,
},
["t"] = 1170743.689,
["kind"] = "context",
["event"] = "UI_INFO_MESSAGE",
["seq"] = 106,
},
{
["t"] = 1170743.809,
["changes"] = {
{
["quest_id"] = 437,
["title"] = "The Dead Fields",
["from"] = false,
["kind"] = "complete_changed",
["to"] = true,
},
{
["quest_id"] = 437,
["title"] = "The Dead Fields",
["from"] = false,
["kind"] = "ready_changed",
["to"] = true,
},
{
["quest_id"] = 437,
["title"] = "The Dead Fields",
["from"] = {
["text"] = "0/1 Essence of Nightlash",
["finished"] = false,
["have"] = 0,
["need"] = 1,
},
["kind"] = "objective_changed",
["to"] = {
["text"] = "1/1 Essence of Nightlash",
["finished"] = true,
["have"] = 1,
["need"] = 1,
},
["index"] = 1,
},
},
["quest_snapshots"] = {
[437] = {
["title"] = "The Dead Fields",
["ready"] = true,
["complete"] = true,
["log_index"] = 12,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "item",
["have"] = 1,
["text_info"] = "present",
["text"] = "1/1 Essence of Nightlash",
["need"] = 1,
["finished"] = true,
},
{
["type"] = "event",
["have"] = 1,
["text_info"] = "present",
["text"] = "Enter the Dead Fields",
["need"] = 1,
["finished"] = true,
},
},
},
},
["meaningful"] = 3,
["seq"] = 107,
["seconds_after_trigger"] = 0,
["kind"] = "change",
["detected_by"] = "event",
["trigger_event"] = "UNIT_QUEST_LOG_CHANGED",
},
{
["seq"] = 108,
["immediate_change_count"] = 3,
["args"] = {
{
["value"] = "player",
["type"] = "string",
},
["n"] = 1,
},
["t"] = 1170743.809,
["kind"] = "event",
["event"] = "UNIT_QUEST_LOG_CHANGED",
},
{
["seq"] = 109,
["immediate_change_count"] = 0,
["args"] = {
["n"] = 0,
},
["t"] = 1170743.829,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 110,
["immediate_change_count"] = 0,
["args"] = {
["n"] = 0,
},
["t"] = 1170744.389,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 111,
["immediate_change_count"] = 0,
["t"] = 1170819.587,
["args"] = {
{
["value"] = 447,
["type"] = "number",
},
["n"] = 1,
},
["arg1_resolved"] = {
["value"] = 447,
["title_if_quest_id"] = "A Recipe For Death",
},
["kind"] = "event",
["event"] = "QUEST_WATCH_UPDATE",
},
{
["args"] = {
{
["value"] = 317,
["type"] = "number",
},
{
["value"] = "Grizzled Bear Heart: 4/6",
["type"] = "string",
},
["n"] = 2,
},
["t"] = 1170819.587,
["kind"] = "context",
["event"] = "UI_INFO_MESSAGE",
["seq"] = 112,
},
{
["t"] = 1170819.647,
["changes"] = {
{
["quest_id"] = 447,
["title"] = "A Recipe For Death",
["from"] = {
["text"] = "3/6 Grizzled Bear Heart",
["finished"] = false,
["have"] = 3,
["need"] = 6,
},
["kind"] = "objective_changed",
["to"] = {
["text"] = "4/6 Grizzled Bear Heart",
["finished"] = false,
["have"] = 4,
["need"] = 6,
},
["index"] = 1,
},
},
["quest_snapshots"] = {
[447] = {
["title"] = "A Recipe For Death",
["ready"] = false,
["complete"] = false,
["log_index"] = 10,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "item",
["have"] = 4,
["text_info"] = "present",
["text"] = "4/6 Grizzled Bear Heart",
["need"] = 6,
["finished"] = false,
},
{
["type"] = "item",
["have"] = 0,
["text_info"] = "present",
["text"] = "0/6 Skittering Blood",
["need"] = 6,
["finished"] = false,
},
},
},
},
["meaningful"] = 1,
["seq"] = 113,
["seconds_after_trigger"] = 0,
["kind"] = "change",
["detected_by"] = "event",
["trigger_event"] = "UNIT_QUEST_LOG_CHANGED",
},
{
["seq"] = 114,
["immediate_change_count"] = 1,
["args"] = {
{
["value"] = "player",
["type"] = "string",
},
["n"] = 1,
},
["t"] = 1170819.647,
["kind"] = "event",
["event"] = "UNIT_QUEST_LOG_CHANGED",
},
{
["seq"] = 115,
["immediate_change_count"] = 0,
["args"] = {
["n"] = 0,
},
["t"] = 1170819.658,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 116,
["immediate_change_count"] = 0,
["args"] = {
["n"] = 0,
},
["t"] = 1170819.928,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 117,
["immediate_change_count"] = 0,
["t"] = 1171239.739,
["args"] = {
{
["value"] = 447,
["type"] = "number",
},
["n"] = 1,
},
["arg1_resolved"] = {
["value"] = 447,
["title_if_quest_id"] = "A Recipe For Death",
},
["kind"] = "event",
["event"] = "QUEST_WATCH_UPDATE",
},
{
["args"] = {
{
["value"] = 317,
["type"] = "number",
},
{
["value"] = "Grizzled Bear Heart: 5/6",
["type"] = "string",
},
["n"] = 2,
},
["t"] = 1171239.739,
["kind"] = "context",
["event"] = "UI_INFO_MESSAGE",
["seq"] = 118,
},
{
["t"] = 1171239.908,
["changes"] = {
{
["quest_id"] = 447,
["title"] = "A Recipe For Death",
["from"] = {
["text"] = "4/6 Grizzled Bear Heart",
["finished"] = false,
["have"] = 4,
["need"] = 6,
},
["kind"] = "objective_changed",
["to"] = {
["text"] = "5/6 Grizzled Bear Heart",
["finished"] = false,
["have"] = 5,
["need"] = 6,
},
["index"] = 1,
},
},
["quest_snapshots"] = {
[447] = {
["title"] = "A Recipe For Death",
["ready"] = false,
["complete"] = false,
["log_index"] = 10,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "item",
["have"] = 5,
["text_info"] = "present",
["text"] = "5/6 Grizzled Bear Heart",
["need"] = 6,
["finished"] = false,
},
{
["type"] = "item",
["have"] = 0,
["text_info"] = "present",
["text"] = "0/6 Skittering Blood",
["need"] = 6,
["finished"] = false,
},
},
},
},
["meaningful"] = 1,
["seq"] = 119,
["seconds_after_trigger"] = 0,
["kind"] = "change",
["detected_by"] = "event",
["trigger_event"] = "UNIT_QUEST_LOG_CHANGED",
},
{
["seq"] = 120,
["immediate_change_count"] = 1,
["args"] = {
{
["value"] = "player",
["type"] = "string",
},
["n"] = 1,
},
["t"] = 1171239.908,
["kind"] = "event",
["event"] = "UNIT_QUEST_LOG_CHANGED",
},
{
["seq"] = 121,
["immediate_change_count"] = 0,
["args"] = {
["n"] = 0,
},
["t"] = 1171239.92,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 122,
["immediate_change_count"] = 0,
["args"] = {
["n"] = 0,
},
["t"] = 1171240.173,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 123,
["immediate_change_count"] = 0,
["t"] = 1171248.892,
["args"] = {
{
["value"] = 429,
["type"] = "number",
},
["n"] = 1,
},
["arg1_resolved"] = {
["value"] = 429,
["title_if_quest_id"] = "Wild Hearts",
},
["kind"] = "event",
["event"] = "QUEST_WATCH_UPDATE",
},
{
["args"] = {
{
["value"] = 317,
["type"] = "number",
},
{
["value"] = "Discolored Worg Heart: 1/3",
["type"] = "string",
},
["n"] = 2,
},
["t"] = 1171248.892,
["kind"] = "context",
["event"] = "UI_INFO_MESSAGE",
["seq"] = 124,
},
{
["t"] = 1171249.048,
["changes"] = {
{
["quest_id"] = 429,
["title"] = "Wild Hearts",
["from"] = {
["text"] = "0/3 Discolored Worg Heart",
["finished"] = false,
["have"] = 0,
["need"] = 3,
},
["kind"] = "objective_changed",
["to"] = {
["text"] = "1/3 Discolored Worg Heart",
["finished"] = false,
["have"] = 1,
["need"] = 3,
},
["index"] = 1,
},
},
["quest_snapshots"] = {
[429] = {
["title"] = "Wild Hearts",
["ready"] = false,
["complete"] = false,
["log_index"] = 9,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "item",
["have"] = 1,
["text_info"] = "present",
["text"] = "1/3 Discolored Worg Heart",
["need"] = 3,
["finished"] = false,
},
},
},
},
["meaningful"] = 1,
["seq"] = 125,
["seconds_after_trigger"] = 0,
["kind"] = "change",
["detected_by"] = "event",
["trigger_event"] = "UNIT_QUEST_LOG_CHANGED",
},
{
["seq"] = 126,
["immediate_change_count"] = 1,
["args"] = {
{
["value"] = "player",
["type"] = "string",
},
["n"] = 1,
},
["t"] = 1171249.048,
["kind"] = "event",
["event"] = "UNIT_QUEST_LOG_CHANGED",
},
{
["seq"] = 127,
["immediate_change_count"] = 0,
["args"] = {
["n"] = 0,
},
["t"] = 1171249.062,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 128,
["immediate_change_count"] = 0,
["args"] = {
["n"] = 0,
},
["t"] = 1171249.694,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 129,
["immediate_change_count"] = 0,
["t"] = 1171349.913,
["args"] = {
{
["value"] = 447,
["type"] = "number",
},
["n"] = 1,
},
["arg1_resolved"] = {
["value"] = 447,
["title_if_quest_id"] = "A Recipe For Death",
},
["kind"] = "event",
["event"] = "QUEST_WATCH_UPDATE",
},
{
["t"] = 1171349.913,
["changes"] = {
{
["quest_id"] = 447,
["title"] = "A Recipe For Death",
["from"] = {
["text"] = "5/6 Grizzled Bear Heart",
["finished"] = false,
["have"] = 5,
["need"] = 6,
},
["kind"] = "objective_changed",
["to"] = {
["text"] = "6/6 Grizzled Bear Heart",
["finished"] = true,
["have"] = 6,
["need"] = 6,
},
["index"] = 1,
},
},
["quest_snapshots"] = {
[447] = {
["title"] = "A Recipe For Death",
["ready"] = false,
["complete"] = false,
["log_index"] = 10,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "item",
["have"] = 6,
["text_info"] = "present",
["text"] = "6/6 Grizzled Bear Heart",
["need"] = 6,
["finished"] = true,
},
{
["type"] = "item",
["have"] = 0,
["text_info"] = "present",
["text"] = "0/6 Skittering Blood",
["need"] = 6,
["finished"] = false,
},
},
},
},
["meaningful"] = 1,
["seq"] = 130,
["seconds_after_trigger"] = 0,
["kind"] = "change",
["detected_by"] = "event",
["trigger_event"] = "UNIT_QUEST_LOG_CHANGED",
},
{
["seq"] = 131,
["immediate_change_count"] = 1,
["args"] = {
{
["value"] = "player",
["type"] = "string",
},
["n"] = 1,
},
["t"] = 1171349.913,
["kind"] = "event",
["event"] = "UNIT_QUEST_LOG_CHANGED",
},
{
["seq"] = 132,
["immediate_change_count"] = 0,
["args"] = {
["n"] = 0,
},
["t"] = 1171349.913,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["args"] = {
{
["value"] = 317,
["type"] = "number",
},
{
["value"] = "Grizzled Bear Heart: 6/6",
["type"] = "string",
},
["n"] = 2,
},
["t"] = 1171349.913,
["kind"] = "context",
["event"] = "UI_INFO_MESSAGE",
["seq"] = 133,
},
{
["seq"] = 134,
["immediate_change_count"] = 0,
["args"] = {
["n"] = 0,
},
["t"] = 1171349.936,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 135,
["immediate_change_count"] = 0,
["args"] = {
["n"] = 0,
},
["t"] = 1171415.599,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 136,
["immediate_change_count"] = 0,
["args"] = {
["n"] = 0,
},
["t"] = 1171453.329,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["args"] = {
{
["value"] = 412,
["type"] = "number",
},
{
["value"] = "Discovered: The Skittering Dark",
["type"] = "string",
},
["n"] = 2,
},
["t"] = 1171470.851,
["kind"] = "context",
["event"] = "UI_INFO_MESSAGE",
["seq"] = 137,
},
{
["seq"] = 138,
["immediate_change_count"] = 0,
["t"] = 1171618.149,
["args"] = {
{
["value"] = 447,
["type"] = "number",
},
["n"] = 1,
},
["arg1_resolved"] = {
["value"] = 447,
["title_if_quest_id"] = "A Recipe For Death",
},
["kind"] = "event",
["event"] = "QUEST_WATCH_UPDATE",
},
{
["args"] = {
{
["value"] = 317,
["type"] = "number",
},
{
["value"] = "Skittering Blood: 1/6",
["type"] = "string",
},
["n"] = 2,
},
["t"] = 1171618.149,
["kind"] = "context",
["event"] = "UI_INFO_MESSAGE",
["seq"] = 139,
},
{
["t"] = 1171618.291,
["changes"] = {
{
["quest_id"] = 447,
["title"] = "A Recipe For Death",
["from"] = {
["text"] = "0/6 Skittering Blood",
["finished"] = false,
["have"] = 0,
["need"] = 6,
},
["kind"] = "objective_changed",
["to"] = {
["text"] = "1/6 Skittering Blood",
["finished"] = false,
["have"] = 1,
["need"] = 6,
},
["index"] = 2,
},
},
["quest_snapshots"] = {
[447] = {
["title"] = "A Recipe For Death",
["ready"] = false,
["complete"] = false,
["log_index"] = 8,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "item",
["have"] = 6,
["text_info"] = "present",
["text"] = "6/6 Grizzled Bear Heart",
["need"] = 6,
["finished"] = true,
},
{
["type"] = "item",
["have"] = 1,
["text_info"] = "present",
["text"] = "1/6 Skittering Blood",
["need"] = 6,
["finished"] = false,
},
},
},
},
["meaningful"] = 1,
["seq"] = 140,
["seconds_after_trigger"] = 0,
["kind"] = "change",
["detected_by"] = "event",
["trigger_event"] = "UNIT_QUEST_LOG_CHANGED",
},
{
["seq"] = 141,
["immediate_change_count"] = 1,
["args"] = {
{
["value"] = "player",
["type"] = "string",
},
["n"] = 1,
},
["t"] = 1171618.291,
["kind"] = "event",
["event"] = "UNIT_QUEST_LOG_CHANGED",
},
{
["seq"] = 142,
["immediate_change_count"] = 0,
["args"] = {
["n"] = 0,
},
["t"] = 1171618.309,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 143,
["immediate_change_count"] = 0,
["args"] = {
["n"] = 0,
},
["t"] = 1171618.876,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 144,
["immediate_change_count"] = 0,
["t"] = 1171640.042,
["args"] = {
{
["value"] = 447,
["type"] = "number",
},
["n"] = 1,
},
["arg1_resolved"] = {
["value"] = 447,
["title_if_quest_id"] = "A Recipe For Death",
},
["kind"] = "event",
["event"] = "QUEST_WATCH_UPDATE",
},
{
["args"] = {
{
["value"] = 317,
["type"] = "number",
},
{
["value"] = "Skittering Blood: 2/6",
["type"] = "string",
},
["n"] = 2,
},
["t"] = 1171640.042,
["kind"] = "context",
["event"] = "UI_INFO_MESSAGE",
["seq"] = 145,
},
{
["t"] = 1171640.133,
["changes"] = {
{
["quest_id"] = 447,
["title"] = "A Recipe For Death",
["from"] = {
["text"] = "1/6 Skittering Blood",
["finished"] = false,
["have"] = 1,
["need"] = 6,
},
["kind"] = "objective_changed",
["to"] = {
["text"] = "2/6 Skittering Blood",
["finished"] = false,
["have"] = 2,
["need"] = 6,
},
["index"] = 2,
},
},
["quest_snapshots"] = {
[447] = {
["title"] = "A Recipe For Death",
["ready"] = false,
["complete"] = false,
["log_index"] = 10,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "item",
["have"] = 6,
["text_info"] = "present",
["text"] = "6/6 Grizzled Bear Heart",
["need"] = 6,
["finished"] = true,
},
{
["type"] = "item",
["have"] = 2,
["text_info"] = "present",
["text"] = "2/6 Skittering Blood",
["need"] = 6,
["finished"] = false,
},
},
},
},
["meaningful"] = 1,
["seq"] = 146,
["seconds_after_trigger"] = 0,
["kind"] = "change",
["detected_by"] = "event",
["trigger_event"] = "UNIT_QUEST_LOG_CHANGED",
},
{
["seq"] = 147,
["immediate_change_count"] = 1,
["args"] = {
{
["value"] = "player",
["type"] = "string",
},
["n"] = 1,
},
["t"] = 1171640.133,
["kind"] = "event",
["event"] = "UNIT_QUEST_LOG_CHANGED",
},
{
["seq"] = 148,
["immediate_change_count"] = 0,
["args"] = {
["n"] = 0,
},
["t"] = 1171640.133,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 149,
["immediate_change_count"] = 0,
["args"] = {
["n"] = 0,
},
["t"] = 1171640.15,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 150,
["immediate_change_count"] = 0,
["t"] = 1171678.597,
["args"] = {
{
["value"] = 447,
["type"] = "number",
},
["n"] = 1,
},
["arg1_resolved"] = {
["value"] = 447,
["title_if_quest_id"] = "A Recipe For Death",
},
["kind"] = "event",
["event"] = "QUEST_WATCH_UPDATE",
},
{
["t"] = 1171678.597,
["changes"] = {
{
["quest_id"] = 447,
["title"] = "A Recipe For Death",
["from"] = {
["text"] = "2/6 Skittering Blood",
["finished"] = false,
["have"] = 2,
["need"] = 6,
},
["kind"] = "objective_changed",
["to"] = {
["text"] = "3/6 Skittering Blood",
["finished"] = false,
["have"] = 3,
["need"] = 6,
},
["index"] = 2,
},
},
["quest_snapshots"] = {
[447] = {
["title"] = "A Recipe For Death",
["ready"] = false,
["complete"] = false,
["log_index"] = 10,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "item",
["have"] = 6,
["text_info"] = "present",
["text"] = "6/6 Grizzled Bear Heart",
["need"] = 6,
["finished"] = true,
},
{
["type"] = "item",
["have"] = 3,
["text_info"] = "present",
["text"] = "3/6 Skittering Blood",
["need"] = 6,
["finished"] = false,
},
},
},
},
["meaningful"] = 1,
["seq"] = 151,
["seconds_after_trigger"] = 0,
["kind"] = "change",
["detected_by"] = "event",
["trigger_event"] = "UNIT_QUEST_LOG_CHANGED",
},
{
["seq"] = 152,
["immediate_change_count"] = 1,
["args"] = {
{
["value"] = "player",
["type"] = "string",
},
["n"] = 1,
},
["t"] = 1171678.597,
["kind"] = "event",
["event"] = "UNIT_QUEST_LOG_CHANGED",
},
{
["seq"] = 153,
["immediate_change_count"] = 0,
["args"] = {
["n"] = 0,
},
["t"] = 1171678.597,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["args"] = {
{
["value"] = 317,
["type"] = "number",
},
{
["value"] = "Skittering Blood: 3/6",
["type"] = "string",
},
["n"] = 2,
},
["t"] = 1171678.597,
["kind"] = "context",
["event"] = "UI_INFO_MESSAGE",
["seq"] = 154,
},
{
["seq"] = 155,
["immediate_change_count"] = 0,
["args"] = {
["n"] = 0,
},
["t"] = 1171678.622,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 156,
["immediate_change_count"] = 0,
["t"] = 1171690.315,
["args"] = {
{
["value"] = 447,
["type"] = "number",
},
["n"] = 1,
},
["arg1_resolved"] = {
["value"] = 447,
["title_if_quest_id"] = "A Recipe For Death",
},
["kind"] = "event",
["event"] = "QUEST_WATCH_UPDATE",
},
{
["args"] = {
{
["value"] = 317,
["type"] = "number",
},
{
["value"] = "Skittering Blood: 4/6",
["type"] = "string",
},
["n"] = 2,
},
["t"] = 1171690.315,
["kind"] = "context",
["event"] = "UI_INFO_MESSAGE",
["seq"] = 157,
},
{
["t"] = 1171690.374,
["changes"] = {
{
["quest_id"] = 447,
["title"] = "A Recipe For Death",
["from"] = {
["text"] = "3/6 Skittering Blood",
["finished"] = false,
["have"] = 3,
["need"] = 6,
},
["kind"] = "objective_changed",
["to"] = {
["text"] = "4/6 Skittering Blood",
["finished"] = false,
["have"] = 4,
["need"] = 6,
},
["index"] = 2,
},
},
["quest_snapshots"] = {
[447] = {
["title"] = "A Recipe For Death",
["ready"] = false,
["complete"] = false,
["log_index"] = 10,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "item",
["have"] = 6,
["text_info"] = "present",
["text"] = "6/6 Grizzled Bear Heart",
["need"] = 6,
["finished"] = true,
},
{
["type"] = "item",
["have"] = 4,
["text_info"] = "present",
["text"] = "4/6 Skittering Blood",
["need"] = 6,
["finished"] = false,
},
},
},
},
["meaningful"] = 1,
["seq"] = 158,
["seconds_after_trigger"] = 0,
["kind"] = "change",
["detected_by"] = "event",
["trigger_event"] = "UNIT_QUEST_LOG_CHANGED",
},
{
["seq"] = 159,
["immediate_change_count"] = 1,
["args"] = {
{
["value"] = "player",
["type"] = "string",
},
["n"] = 1,
},
["t"] = 1171690.374,
["kind"] = "event",
["event"] = "UNIT_QUEST_LOG_CHANGED",
},
{
["seq"] = 160,
["immediate_change_count"] = 0,
["args"] = {
["n"] = 0,
},
["t"] = 1171690.383,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 161,
["immediate_change_count"] = 0,
["args"] = {
["n"] = 0,
},
["t"] = 1171690.793,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 162,
["immediate_change_count"] = 0,
["args"] = {
["n"] = 0,
},
["t"] = 1171772.437,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 163,
["immediate_change_count"] = 0,
["args"] = {
["n"] = 0,
},
["t"] = 1171773.646,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 164,
["immediate_change_count"] = 0,
["t"] = 1171817.895,
["args"] = {
{
["value"] = 447,
["type"] = "number",
},
["n"] = 1,
},
["arg1_resolved"] = {
["value"] = 447,
["title_if_quest_id"] = "A Recipe For Death",
},
["kind"] = "event",
["event"] = "QUEST_WATCH_UPDATE",
},
{
["t"] = 1171817.895,
["changes"] = {
{
["quest_id"] = 447,
["title"] = "A Recipe For Death",
["from"] = {
["text"] = "4/6 Skittering Blood",
["finished"] = false,
["have"] = 4,
["need"] = 6,
},
["kind"] = "objective_changed",
["to"] = {
["text"] = "5/6 Skittering Blood",
["finished"] = false,
["have"] = 5,
["need"] = 6,
},
["index"] = 2,
},
},
["quest_snapshots"] = {
[447] = {
["title"] = "A Recipe For Death",
["ready"] = false,
["complete"] = false,
["log_index"] = 8,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "item",
["have"] = 6,
["text_info"] = "present",
["text"] = "6/6 Grizzled Bear Heart",
["need"] = 6,
["finished"] = true,
},
{
["type"] = "item",
["have"] = 5,
["text_info"] = "present",
["text"] = "5/6 Skittering Blood",
["need"] = 6,
["finished"] = false,
},
},
},
},
["meaningful"] = 1,
["seq"] = 165,
["seconds_after_trigger"] = 0,
["kind"] = "change",
["detected_by"] = "event",
["trigger_event"] = "UNIT_QUEST_LOG_CHANGED",
},
{
["seq"] = 166,
["immediate_change_count"] = 1,
["args"] = {
{
["value"] = "player",
["type"] = "string",
},
["n"] = 1,
},
["t"] = 1171817.895,
["kind"] = "event",
["event"] = "UNIT_QUEST_LOG_CHANGED",
},
{
["seq"] = 167,
["immediate_change_count"] = 0,
["args"] = {
{
["value"] = "targettarget",
["type"] = "string",
},
["n"] = 1,
},
["t"] = 1171817.895,
["kind"] = "event",
["event"] = "UNIT_QUEST_LOG_CHANGED",
},
{
["seq"] = 168,
["immediate_change_count"] = 0,
["args"] = {
["n"] = 0,
},
["t"] = 1171817.895,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["args"] = {
{
["value"] = 317,
["type"] = "number",
},
{
["value"] = "Skittering Blood: 5/6",
["type"] = "string",
},
["n"] = 2,
},
["t"] = 1171817.895,
["kind"] = "context",
["event"] = "UI_INFO_MESSAGE",
["seq"] = 169,
},
{
["seq"] = 170,
["immediate_change_count"] = 0,
["args"] = {
["n"] = 0,
},
["t"] = 1171817.917,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 171,
["immediate_change_count"] = 0,
["t"] = 1171830.433,
["args"] = {
{
["value"] = 447,
["type"] = "number",
},
["n"] = 1,
},
["arg1_resolved"] = {
["value"] = 447,
["title_if_quest_id"] = "A Recipe For Death",
},
["kind"] = "event",
["event"] = "QUEST_WATCH_UPDATE",
},
{
["args"] = {
{
["value"] = 317,
["type"] = "number",
},
{
["value"] = "Skittering Blood: 6/6",
["type"] = "string",
},
["n"] = 2,
},
["t"] = 1171830.433,
["kind"] = "context",
["event"] = "UI_INFO_MESSAGE",
["seq"] = 172,
},
{
["args"] = {
{
["value"] = 314,
["type"] = "number",
},
{
["value"] = "Objective Complete.",
["type"] = "string",
},
["n"] = 2,
},
["t"] = 1171830.433,
["kind"] = "context",
["event"] = "UI_INFO_MESSAGE",
["seq"] = 173,
},
{
["t"] = 1171830.484,
["changes"] = {
{
["quest_id"] = 447,
["title"] = "A Recipe For Death",
["from"] = false,
["kind"] = "complete_changed",
["to"] = true,
},
{
["quest_id"] = 447,
["title"] = "A Recipe For Death",
["from"] = false,
["kind"] = "ready_changed",
["to"] = true,
},
{
["quest_id"] = 447,
["title"] = "A Recipe For Death",
["from"] = {
["text"] = "5/6 Skittering Blood",
["finished"] = false,
["have"] = 5,
["need"] = 6,
},
["kind"] = "objective_changed",
["to"] = {
["text"] = "6/6 Skittering Blood",
["finished"] = true,
["have"] = 6,
["need"] = 6,
},
["index"] = 2,
},
},
["quest_snapshots"] = {
[447] = {
["title"] = "A Recipe For Death",
["ready"] = true,
["complete"] = true,
["log_index"] = 10,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "item",
["have"] = 6,
["text_info"] = "present",
["text"] = "6/6 Grizzled Bear Heart",
["need"] = 6,
["finished"] = true,
},
{
["type"] = "item",
["have"] = 6,
["text_info"] = "present",
["text"] = "6/6 Skittering Blood",
["need"] = 6,
["finished"] = true,
},
},
},
},
["meaningful"] = 3,
["seq"] = 174,
["seconds_after_trigger"] = 0,
["kind"] = "change",
["detected_by"] = "event",
["trigger_event"] = "UNIT_QUEST_LOG_CHANGED",
},
{
["seq"] = 175,
["immediate_change_count"] = 3,
["args"] = {
{
["value"] = "player",
["type"] = "string",
},
["n"] = 1,
},
["t"] = 1171830.484,
["kind"] = "event",
["event"] = "UNIT_QUEST_LOG_CHANGED",
},
{
["seq"] = 176,
["immediate_change_count"] = 0,
["args"] = {
["n"] = 0,
},
["t"] = 1171830.492,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 177,
["immediate_change_count"] = 0,
["args"] = {
["n"] = 0,
},
["t"] = 1171830.858,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 178,
["immediate_change_count"] = 0,
["args"] = {
["n"] = 0,
},
["t"] = 1171846.674,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 179,
["immediate_change_count"] = 0,
["args"] = {
["n"] = 0,
},
["t"] = 1171884.044,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["seq"] = 180,
["immediate_change_count"] = 0,
["args"] = {
["n"] = 0,
},
["t"] = 1171893.696,
["kind"] = "event",
["event"] = "QUEST_LOG_UPDATE",
},
{
["t"] = 1171986.073,
["kind"] = "manual_snapshot",
["seq"] = 181,
["snapshot"] = {
[1013] = {
["title"] = "The Book of Ur",
["ready"] = false,
["complete"] = false,
["log_index"] = 3,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "item",
["have"] = 0,
["text_info"] = "present",
["text"] = "0/1 The Book of Ur",
["need"] = 1,
["finished"] = false,
},
},
},
[98024] = {
["title"] = "Journey to the Crossroads",
["ready"] = true,
["complete"] = true,
["log_index"] = 16,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
},
},
[429] = {
["title"] = "Wild Hearts",
["ready"] = false,
["complete"] = false,
["log_index"] = 7,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "item",
["have"] = 1,
["text_info"] = "present",
["text"] = "1/3 Discolored Worg Heart",
["need"] = 3,
["finished"] = false,
},
},
},
[447] = {
["title"] = "A Recipe For Death",
["ready"] = true,
["complete"] = true,
["log_index"] = 8,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "item",
["have"] = 6,
["text_info"] = "present",
["text"] = "6/6 Grizzled Bear Heart",
["need"] = 6,
["finished"] = true,
},
{
["type"] = "item",
["have"] = 6,
["text_info"] = "present",
["text"] = "6/6 Skittering Blood",
["need"] = 6,
["finished"] = true,
},
},
},
[1014] = {
["title"] = "Arugal Must Die",
["ready"] = false,
["complete"] = false,
["log_index"] = 4,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "item",
["have"] = 0,
["text_info"] = "present",
["text"] = "0/1 Head of Arugal",
["need"] = 1,
["finished"] = false,
},
},
},
[1098] = {
["title"] = "Deathstalkers in Shadowfang",
["ready"] = true,
["complete"] = true,
["log_index"] = 2,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
},
},
[93739] = {
["title"] = "Exploring the Horde",
["ready"] = true,
["complete"] = true,
["log_index"] = 14,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "monster",
["have"] = 1,
["text_info"] = "present",
["text"] = "1/1 Obtain Instructions from Nazgrel",
["need"] = 1,
["finished"] = true,
},
{
["type"] = "monster",
["have"] = 1,
["text_info"] = "present",
["text"] = "1/1 Speak with Vol'jin",
["need"] = 1,
["finished"] = true,
},
{
["type"] = "monster",
["have"] = 1,
["text_info"] = "present",
["text"] = "1/1 Speak with Cairne Bloodhoof",
["need"] = 1,
["finished"] = true,
},
{
["type"] = "monster",
["have"] = 1,
["text_info"] = "present",
["text"] = "1/1 Speak with Lady Sylvanas Windrunner",
["need"] = 1,
["finished"] = true,
},
},
},
[421] = {
["title"] = "Prove Your Worth",
["ready"] = false,
["complete"] = false,
["log_index"] = 6,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "monster",
["have"] = 0,
["text_info"] = "present",
["text"] = "0/5 Moonrage Whitescalp slain",
["need"] = 5,
["finished"] = false,
},
},
},
[437] = {
["title"] = "The Dead Fields",
["ready"] = true,
["complete"] = true,
["log_index"] = 10,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "item",
["have"] = 1,
["text_info"] = "present",
["text"] = "1/1 Essence of Nightlash",
["need"] = 1,
["finished"] = true,
},
{
["type"] = "event",
["have"] = 1,
["text_info"] = "present",
["text"] = "Enter the Dead Fields",
["need"] = 1,
["finished"] = true,
},
},
},
[493] = {
["title"] = "Journey to Hillsbrad Foothills",
["ready"] = true,
["complete"] = true,
["log_index"] = 11,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "log",
["have"] = 1,
["text_info"] = "present",
["text"] = "Deliver Apothecary Renferrel's findings to Apothecary Lydon in the town of Tarren Mill in the Hillsbrad Foothills.",
["need"] = 1,
["finished"] = true,
},
},
},
[516] = {
["title"] = "Beren's Peril",
["ready"] = false,
["complete"] = false,
["log_index"] = 12,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
{
["type"] = "monster",
["have"] = 0,
["text_info"] = "present",
["text"] = "0/6 Ravenclaw Drudger slain",
["need"] = 6,
["finished"] = false,
},
{
["type"] = "monster",
["have"] = 0,
["text_info"] = "present",
["text"] = "0/6 Ravenclaw Guardian slain",
["need"] = 6,
["finished"] = false,
},
},
},
[477] = {
["title"] = "Border Crossings",
["ready"] = true,
["complete"] = true,
["log_index"] = 9,
["source"] = "C_QuestLog.GetQuestObjectives",
["objectives"] = {
},
},
},
},
},
["onupdate_ticks"] = 277097,
["started_t"] = 1170001.345,
["game_version"] = "1.60.1",
["baseline_t"] = 1170004.349,
["apis"] = {
["C_QuestLog.ReadyForTurnIn"] = "function",
["C_QuestLog.IsComplete"] = "function",
["C_Timer.After"] = "function (not used)",
["C_QuestLog.GetInfo"] = "function",
["C_QuestLog.GetTitleForQuestID"] = "function",
["GetQuestLogLeaderBoard"] = "function",
["C_QuestLog.GetQuestObjectives"] = "function",
["GetNumQuestLogEntries"] = "absent",
["GetNumQuestLeaderBoards"] = "function",
["C_QuestLog.GetNumQuestLogEntries"] = "function",
["GetQuestLogTitle"] = "absent",
},
["counts"] = {
["QUEST_REMOVED"] = 2,
["UNIT_QUEST_LOG_CHANGED"] = 28,
["complete_changed:event"] = 4,
["QUEST_TURNED_IN"] = 2,
["QUEST_LOG_UPDATE"] = 65,
["UI_INFO_MESSAGE"] = 21,
["objective_change:event"] = 24,
["QUEST_WATCH_UPDATE"] = 16,
["quest_added"] = 10,
["QUEST_ACCEPTED"] = 10,
["ready_changed:event"] = 3,
["quest_removed"] = 2,
},
["build"] = "70124",
},
},
}
